// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gdproto/options.proto

package gdprotopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_gdproto_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51000,
		Name:          "gdproto.class_prefix",
		Tag:           "bytes,51000,opt,name=class_prefix",
		Filename:      "gdproto/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// class_prefix is prepended to every GDScript class name generated from
	// this .proto file. It is used to disambiguate class names when generating
	// one .gd file per message/enum.
	//
	// optional string class_prefix = 51000;
	E_ClassPrefix = &file_gdproto_options_proto_extTypes[0]
)

var File_gdproto_options_proto protoreflect.FileDescriptor

const file_gdproto_options_proto_rawDesc = "" +
	"\n" +
	"\x15gdproto/options.proto\x12\agdproto\x1a google/protobuf/descriptor.proto:A\n" +
	"\fclass_prefix\x12\x1c.google.protobuf.FileOptions\x18\xb8\x8e\x03 \x01(\tR\vclassPrefixB6Z4github.com/cafecito-games/gdproto/internal/gdprotopb"

var file_gdproto_options_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil), // 0: google.protobuf.FileOptions
}
var file_gdproto_options_proto_depIdxs = []int32{
	0, // 0: gdproto.class_prefix:extendee -> google.protobuf.FileOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gdproto_options_proto_init() }
func file_gdproto_options_proto_init() {
	if File_gdproto_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gdproto_options_proto_rawDesc), len(file_gdproto_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_gdproto_options_proto_goTypes,
		DependencyIndexes: file_gdproto_options_proto_depIdxs,
		ExtensionInfos:    file_gdproto_options_proto_extTypes,
	}.Build()
	File_gdproto_options_proto = out.File
	file_gdproto_options_proto_goTypes = nil
	file_gdproto_options_proto_depIdxs = nil
}
