class_name ExamplePlayer

extends RefCounted

# Generated by gdproto
# Source: example.proto
# DO NOT EDIT

# Fields
var _username: String = ""
var _level: int = 0
var _experience: int = 0
var _status: ExamplePlayerStatus.PlayerStatus = 0 as ExamplePlayerStatus.PlayerStatus
var _inventory: Array[String] = []
var _position: ExamplePlayerPosition = null
var _email: String = ""
var _discord: String = ""
var _stats: Dictionary[String, int] = {}
var _status_effects: Dictionary[String, ExamplePlayerStatus.PlayerStatus] = {}

# Oneof enums

enum ContactOneOf {
	UNSET = 0,
	EMAIL = 1,
	DISCORD = 2
}

# Oneof tracking
var _oneof_contact: ContactOneOf = ContactOneOf.UNSET

# Accessors

func set_username(value: String) -> void:
	_username = value

func get_username() -> String:
	return _username

func set_level(value: int) -> void:
	_level = value

func get_level() -> int:
	return _level

func set_experience(value: int) -> void:
	_experience = value

func get_experience() -> int:
	return _experience

func set_status(value: ExamplePlayerStatus.PlayerStatus) -> void:
	_status = value

func get_status() -> ExamplePlayerStatus.PlayerStatus:
	return _status

func add_inventory(value: String) -> void:
	_inventory.append(value)

func get_inventory() -> Array[String]:
	return _inventory

func new_position() -> ExamplePlayerPosition:
	_position = ExamplePlayerPosition.new()
	return _position

func get_position() -> ExamplePlayerPosition:
	return _position

func set_email(value: String) -> void:
	if _oneof_contact != ContactOneOf.EMAIL:
		_discord = ""
		_oneof_contact = ContactOneOf.EMAIL
	_email = value

func get_email() -> String:
	return _email

func has_email() -> bool:
	return _oneof_contact == ContactOneOf.EMAIL

func set_discord(value: String) -> void:
	if _oneof_contact != ContactOneOf.DISCORD:
		_email = ""
		_oneof_contact = ContactOneOf.DISCORD
	_discord = value

func get_discord() -> String:
	return _discord

func has_discord() -> bool:
	return _oneof_contact == ContactOneOf.DISCORD

func add_stats(key: String, value: int) -> void:
	_stats[key] = value

func get_stats() -> Dictionary[String, int]:
	return _stats

func add_status_effects(key: String, value: ExamplePlayerStatus.PlayerStatus) -> void:
	_status_effects[key] = value

func get_status_effects() -> Dictionary[String, ExamplePlayerStatus.PlayerStatus]:
	return _status_effects

# Oneof case getters

func get_contact_case() -> ContactOneOf:
	return _oneof_contact

# Enum name lookup helpers

func _get_enum_name_status(value: int) -> String:
	"""Get enum name for status value."""
	match value:
		ExamplePlayerStatus.PlayerStatus.OFFLINE:
			return "OFFLINE"
		ExamplePlayerStatus.PlayerStatus.ONLINE:
			return "ONLINE"
		ExamplePlayerStatus.PlayerStatus.AWAY:
			return "AWAY"
		ExamplePlayerStatus.PlayerStatus.IN_GAME:
			return "IN_GAME"
		_:
			return str(value)

func _parse_enum_value_status(name: String) -> int:
	"""Parse enum value from name for status."""
	match name:
		"OFFLINE":
			return ExamplePlayerStatus.PlayerStatus.OFFLINE
		"ONLINE":
			return ExamplePlayerStatus.PlayerStatus.ONLINE
		"AWAY":
			return ExamplePlayerStatus.PlayerStatus.AWAY
		"IN_GAME":
			return ExamplePlayerStatus.PlayerStatus.IN_GAME
		_:
			return 0

# Serialization

func to_bytes() -> PackedByteArray:
	"""Serialize message to bytes."""
	var result: PackedByteArray = PackedByteArray()
	# Field username
	if _username != "":
		result.append_array(ProtoCoreUtils.encode_varint(10))
		var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_username)
		result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
		result.append_array(str_data)
	# Field level
	if _level != 0:
		result.append_array(ProtoCoreUtils.encode_varint(16))
		result.append_array(ProtoCoreUtils.encode_varint(_level))
	# Field experience
	if _experience != 0:
		result.append_array(ProtoCoreUtils.encode_varint(24))
		result.append_array(ProtoCoreUtils.encode_varint(_experience))
	# Field status
	if _status != 0:
		result.append_array(ProtoCoreUtils.encode_varint(32))
		result.append_array(ProtoCoreUtils.encode_varint(_status))
	# Field inventory (repeated)
	for item in _inventory:
		result.append_array(ProtoCoreUtils.encode_varint(42))
		var str_data: PackedByteArray = ProtoCoreUtils.encode_string(item)
		result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
		result.append_array(str_data)
	# Field position
	if _position != null:
		result.append_array(ProtoCoreUtils.encode_varint(58))
		var msg_data: PackedByteArray = _position.to_bytes()
		result.append_array(ProtoCoreUtils.encode_varint(msg_data.size()))
		result.append_array(msg_data)
	# Oneof group contact
	match _oneof_contact:
		ContactOneOf.EMAIL:
			# Field email
			result.append_array(ProtoCoreUtils.encode_varint(66))
			var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_email)
			result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
			result.append_array(str_data)
		ContactOneOf.DISCORD:
			# Field discord
			result.append_array(ProtoCoreUtils.encode_varint(74))
			var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_discord)
			result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
			result.append_array(str_data)
	# Map field stats
	for key in _stats:
		var value: int = _stats[key]

		# Build map entry
		var entry: PackedByteArray = PackedByteArray()

		# Entry field 1: key
		entry.append_array(ProtoCoreUtils.encode_varint(10))
		var key_data: PackedByteArray = ProtoCoreUtils.encode_string(key)
		entry.append_array(ProtoCoreUtils.encode_varint(key_data.size()))
		entry.append_array(key_data)

		# Entry field 2: value
		entry.append_array(ProtoCoreUtils.encode_varint(16))
		entry.append_array(ProtoCoreUtils.encode_varint(value))

		# Append entry to result
		result.append_array(ProtoCoreUtils.encode_varint(50))
		result.append_array(ProtoCoreUtils.encode_varint(entry.size()))
		result.append_array(entry)
	# Map field status_effects
	for key in _status_effects:
		var value: ExamplePlayerStatus.PlayerStatus = _status_effects[key]

		# Build map entry
		var entry: PackedByteArray = PackedByteArray()

		# Entry field 1: key
		entry.append_array(ProtoCoreUtils.encode_varint(10))
		var key_data: PackedByteArray = ProtoCoreUtils.encode_string(key)
		entry.append_array(ProtoCoreUtils.encode_varint(key_data.size()))
		entry.append_array(key_data)

		# Entry field 2: value
		entry.append_array(ProtoCoreUtils.encode_varint(16))
		entry.append_array(ProtoCoreUtils.encode_varint(value))

		# Append entry to result
		result.append_array(ProtoCoreUtils.encode_varint(82))
		result.append_array(ProtoCoreUtils.encode_varint(entry.size()))
		result.append_array(entry)
	return result

func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from bytes."""
	var offset: int = 0

	while offset < data.size():
		# Read field tag
		var tag_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
		if tag_result["size"] == -1:
			return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
		var tag: int = tag_result["value"]
		offset += tag_result["size"]

		var field_number: int = ProtoCoreUtils.get_field_number(tag)
		var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

		match field_number:
			1:
				# Field username
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				_username = ProtoCoreUtils.decode_string(data, offset, length)
				offset += length
			2:
				# Field level
				var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
				_level = result["value"]
				offset += result["size"]
			3:
				# Field experience
				var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
				_experience = result["value"]
				offset += result["size"]
			4:
				# Field status
				var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
				_status = result["value"] as ExamplePlayerStatus.PlayerStatus
				offset += result["size"]
			5:
				# Field inventory
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				_inventory.append(ProtoCoreUtils.decode_string(data, offset, length))
				offset += length
			7:
				# Field position
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				var msg_data: PackedByteArray = data.slice(offset, offset + length)
				_position = ExamplePlayerPosition.new()
				var msg_result: ProtoCoreUtils.ProtobufError = _position.from_bytes(msg_data)
				if msg_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
					return msg_result
				offset += length
			6:
				# Map field stats
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH

				var entry_data: PackedByteArray = data.slice(offset, offset + length)
				var entry_offset: int = 0

				var map_key: String = ""
				var map_value: int = 0

				while entry_offset < entry_data.size():
					var entry_tag_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
					if entry_tag_result["size"] == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					var entry_tag: int = entry_tag_result["value"]
					entry_offset += entry_tag_result["size"]
					var entry_field_number: int = ProtoCoreUtils.get_field_number(entry_tag)

					match entry_field_number:
						1:
							# Entry key
							var len_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
							if len_result["size"] == -1:
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
							entry_offset += len_result["size"]
							var str_len: int = len_result["value"]
							if entry_offset + str_len > entry_data.size():
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
							map_key = ProtoCoreUtils.decode_string(entry_data, entry_offset, str_len)
							entry_offset += str_len
						2:
							# Entry value
							var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
							if result["size"] == -1:
								return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
							map_value = result["value"]
							entry_offset += result["size"]

				_stats[map_key] = map_value
				offset += length
			10:
				# Map field status_effects
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH

				var entry_data: PackedByteArray = data.slice(offset, offset + length)
				var entry_offset: int = 0

				var map_key: String = ""
				var map_value: ExamplePlayerStatus.PlayerStatus = 0 as ExamplePlayerStatus.PlayerStatus

				while entry_offset < entry_data.size():
					var entry_tag_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
					if entry_tag_result["size"] == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					var entry_tag: int = entry_tag_result["value"]
					entry_offset += entry_tag_result["size"]
					var entry_field_number: int = ProtoCoreUtils.get_field_number(entry_tag)

					match entry_field_number:
						1:
							# Entry key
							var len_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
							if len_result["size"] == -1:
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
							entry_offset += len_result["size"]
							var str_len: int = len_result["value"]
							if entry_offset + str_len > entry_data.size():
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
							map_key = ProtoCoreUtils.decode_string(entry_data, entry_offset, str_len)
							entry_offset += str_len
						2:
							# Entry value
							var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(entry_data, entry_offset)
							if result["size"] == -1:
								return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
							map_value = result["value"] as ExamplePlayerStatus.PlayerStatus
							entry_offset += result["size"]

				_status_effects[map_key] = map_value
				offset += length
			8:
				# Field email
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				_email = ProtoCoreUtils.decode_string(data, offset, length)
				offset += length
				_oneof_contact = ContactOneOf.EMAIL
			9:
				# Field discord
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				_discord = ProtoCoreUtils.decode_string(data, offset, length)
				offset += length
				_oneof_contact = ContactOneOf.DISCORD
			_:
				# Skip unknown field
				match wire_type:
					0:  # Varint
						var skip_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
						if skip_result["size"] == -1:
							return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
						offset += skip_result["size"]
					1:  # Fixed64
						offset += 8
					2:  # Length-delimited
						var skip_length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
						if skip_length_result["size"] == -1:
							return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
						offset += skip_length_result["size"] + skip_length_result["value"]
					5:  # Fixed32
						offset += 4
					_:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func to_text(indent_level: int = 0) -> String:
	"""Serialize message to protobuf text format."""
	var result: String = ""
	var indent: String = "\t".repeat(indent_level)

	# Field username
	if _username != "":
		result += indent + "username: \"" + ProtoCoreUtils.escape_string_text_format(_username) + "\"\n"

	# Field level
	if _level != 0:
		result += indent + "level: " + str(_level) + "\n"

	# Field experience
	if _experience != 0:
		result += indent + "experience: " + str(_experience) + "\n"

	# Field status
	if _status != 0:
		result += indent + "status: " + _get_enum_name_status(_status) + "\n"

	# Repeated field inventory
	for item in _inventory:
		result += indent + "inventory: \"" + ProtoCoreUtils.escape_string_text_format(item) + "\"\n"

	# Field position
	if _position != null:
		result += indent + "position {\n"
		result += _position.to_text(indent_level + 1)
		result += indent + "}\n"

	# Oneof group: contact
	match _oneof_contact:
		ContactOneOf.EMAIL:
			result += indent + "email: \"" + ProtoCoreUtils.escape_string_text_format(_email) + "\"\n"
		ContactOneOf.DISCORD:
			result += indent + "discord: \"" + ProtoCoreUtils.escape_string_text_format(_discord) + "\"\n"

	# Map field stats
	for key in _stats:
		var value: int = _stats[key]
		result += indent + "stats {\n"
		var inner_indent: String = "\t".repeat(indent_level + 1)

		result += inner_indent + "key: \"" + ProtoCoreUtils.escape_string_text_format(key) + "\"\n"
		result += inner_indent + "value: " + str(value) + "\n"

		result += indent + "}\n"

	# Map field status_effects
	for key in _status_effects:
		var value: ExamplePlayerStatus.PlayerStatus = _status_effects[key]
		result += indent + "status_effects {\n"
		var inner_indent: String = "\t".repeat(indent_level + 1)

		result += inner_indent + "key: \"" + ProtoCoreUtils.escape_string_text_format(key) + "\"\n"
		result += inner_indent + "value: " + str(value) + "\n"

		result += indent + "}\n"

	return result

func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from protobuf text format."""
	var pos: int = 0

	while pos < text.length():
		# Skip whitespace and comments
		pos = ProtoCoreUtils.skip_whitespace(text, pos)
		if pos >= text.length():
			break

		# Parse field name
		var name_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_identifier(text, pos)
		if "error" in name_result:
			push_error(name_result["error"])
			return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
		var field_name: String = name_result["value"]
		pos = name_result["pos"]

		# Skip whitespace before colon
		pos = ProtoCoreUtils.skip_whitespace(text, pos)

		# Match field name and parse value
		match field_name:
			"username":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
				if "error" in str_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_username = str_result["value"]
				pos = str_result["pos"]
			"level":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var num_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
				if num_result.has_error():
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_level = num_result.int_value
				pos = num_result.pos
			"experience":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var num_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
				if num_result.has_error():
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_experience = num_result.int_value
				pos = num_result.pos
			"status":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				# Parse enum value (name or number)
				if pos < text.length() and not text[pos].is_valid_int() and text[pos] != "-":
					# Parse as identifier (enum name)
					var enum_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_identifier(text, pos)
					if "error" not in enum_result:
						var enum_name: String = enum_result["value"]
						var enum_value: int = _parse_enum_value_status(enum_name)
						_status = enum_value as ExamplePlayerStatus.PlayerStatus
						pos = enum_result["pos"]
				else:
					# Parse as number
					var enum_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
					if enum_result.has_error():
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_status = enum_result.int_value as ExamplePlayerStatus.PlayerStatus
					pos = enum_result.pos
			"inventory":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
				if "error" in str_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_inventory.append(str_result["value"])
				pos = str_result["pos"]
			"position":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				# Parse message
				if pos < text.length() and text[pos] == "{":
					pos = pos + 1  # Skip opening brace
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					# Extract message body
					var msg_start: int = pos
					var depth: int = 1
					while pos < text.length() and depth > 0:
						if text[pos] == "{":
							depth = depth + 1
						elif text[pos] == "}":
							depth = depth - 1
							if depth == 0:
								break
						pos = pos + 1

					var msg_text: String = text.substr(msg_start, pos - msg_start)
					pos = pos + 1  # Skip closing brace

					_position = ExamplePlayerPosition.new()
					var parse_result: ProtoCoreUtils.ProtobufError = _position.from_text(msg_text)
					if parse_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
						return parse_result
			"email":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
				if "error" in str_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_email = str_result["value"]
				_oneof_contact = ContactOneOf.EMAIL
				pos = str_result["pos"]
			"discord":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
				if "error" in str_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_discord = str_result["value"]
				_oneof_contact = ContactOneOf.DISCORD
				pos = str_result["pos"]
			"stats":
				# Parse map entry
				if pos < text.length() and text[pos] == ":":
					pos += 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos < text.length() and text[pos] == "{":
					pos += 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var map_key: String = ""
					var map_value: int = 0

					# Parse key and value
					while pos < text.length() and text[pos] != "}":
						var entry_name_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_identifier(text, pos)
						if "error" in entry_name_result:
							break
						var entry_field: String = entry_name_result["value"]
						pos = entry_name_result["pos"]
						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == ":":
							pos += 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						if entry_field == "key":
							var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
							if "value" in str_result:
								map_key = str_result["value"]
								pos = str_result["pos"]
						elif entry_field == "value":
							var num_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
							if not num_result.has_error():
								map_value = num_result.int_value
								pos = num_result.pos

						pos = ProtoCoreUtils.skip_whitespace(text, pos)

					if map_key != null and map_value != null:
						_stats[map_key] = map_value

					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "}":
						pos += 1
			"status_effects":
				# Parse map entry
				if pos < text.length() and text[pos] == ":":
					pos += 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos < text.length() and text[pos] == "{":
					pos += 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var map_key: String = ""
					var map_value: ExamplePlayerStatus.PlayerStatus = 0 as ExamplePlayerStatus.PlayerStatus

					# Parse key and value
					while pos < text.length() and text[pos] != "}":
						var entry_name_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_identifier(text, pos)
						if "error" in entry_name_result:
							break
						var entry_field: String = entry_name_result["value"]
						pos = entry_name_result["pos"]
						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == ":":
							pos += 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						if entry_field == "key":
							var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
							if "value" in str_result:
								map_key = str_result["value"]
								pos = str_result["pos"]
						elif entry_field == "value":
							var num_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
							if not num_result.has_error():
								map_value = num_result.int_value as ExamplePlayerStatus.PlayerStatus
								pos = num_result.pos

						pos = ProtoCoreUtils.skip_whitespace(text, pos)

					if map_key != null and map_value != null:
						_status_effects[map_key] = map_value

					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "}":
						pos += 1
			_:
				# Unknown field - skip it
				push_warning("Unknown field: " + field_name)
				# Try to skip the value
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "{":
						# Skip message body
						var depth: int = 1
						pos = pos + 1
						while pos < text.length() and depth > 0:
							if text[pos] == "{":
								depth = depth + 1
							elif text[pos] == "}":
								depth = depth - 1
							pos = pos + 1
					else:
						# Skip to next field
						while pos < text.length() and text[pos] not in ["\n", "#"]:
							pos = pos + 1

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func _to_string() -> String:
	"""Generate debug string representation."""
	var parts: Array[String] = []

	if _username != "":
		parts.append("username: " + str(_username))
	if _level != 0:
		parts.append("level: " + str(_level))
	if _experience != 0:
		parts.append("experience: " + str(_experience))
	if _status != 0:
		parts.append("status: " + str(_status))
	if _inventory.size() > 0:
		parts.append("inventory: " + str(_inventory))
	if _position != null:
		parts.append("position: " + str(_position))
	if _stats.size() > 0:
		parts.append("stats: " + str(_stats))
	if _status_effects.size() > 0:
		parts.append("status_effects: " + str(_status_effects))
	if _email != "":
		parts.append("email: " + str(_email))
	if _discord != "":
		parts.append("discord: " + str(_discord))

	return "Player { " + ", ".join(parts) + " }"
