class_name ExampleGameState

extends RefCounted

# Generated by gdproto
# Source: example.proto
# DO NOT EDIT

# Fields
var _players: Array[ExamplePlayer] = []
var _timestamp: int = 0
var _map_name: String = ""

# Accessors

func add_players() -> ExamplePlayer:
	var item: ExamplePlayer = ExamplePlayer.new()
	_players.append(item)
	return item

func get_players() -> Array[ExamplePlayer]:
	return _players

func set_timestamp(value: int) -> void:
	_timestamp = value

func get_timestamp() -> int:
	return _timestamp

func set_map_name(value: String) -> void:
	_map_name = value

func get_map_name() -> String:
	return _map_name

# Serialization

func to_bytes() -> PackedByteArray:
	"""Serialize message to bytes."""
	var result: PackedByteArray = PackedByteArray()
	# Field players (repeated)
	for item in _players:
		result.append_array(ProtoCoreUtils.encode_varint(10))
		var msg_data: PackedByteArray = item.to_bytes()
		result.append_array(ProtoCoreUtils.encode_varint(msg_data.size()))
		result.append_array(msg_data)
	# Field timestamp
	if _timestamp != 0:
		result.append_array(ProtoCoreUtils.encode_varint(16))
		result.append_array(ProtoCoreUtils.encode_varint(_timestamp))
	# Field map_name
	if _map_name != "":
		result.append_array(ProtoCoreUtils.encode_varint(26))
		var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_map_name)
		result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
		result.append_array(str_data)
	return result

func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from bytes."""
	var offset: int = 0

	while offset < data.size():
		# Read field tag
		var tag_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
		if tag_result["size"] == -1:
			return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
		var tag: int = tag_result["value"]
		offset += tag_result["size"]

		var field_number: int = ProtoCoreUtils.get_field_number(tag)
		var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

		match field_number:
			1:
				# Field players
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				var msg_data: PackedByteArray = data.slice(offset, offset + length)
				var msg_item: ExamplePlayer = ExamplePlayer.new()
				var msg_result: ProtoCoreUtils.ProtobufError = msg_item.from_bytes(msg_data)
				if msg_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
					return msg_result
				_players.append(msg_item)
				offset += length
			2:
				# Field timestamp
				var result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
				_timestamp = result["value"]
				offset += result["size"]
			3:
				# Field map_name
				var length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
				if length_result["size"] == -1:
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
				offset += length_result["size"]
				var length: int = length_result["value"]
				if offset + length > data.size():
					return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
				_map_name = ProtoCoreUtils.decode_string(data, offset, length)
				offset += length
			_:
				# Skip unknown field
				match wire_type:
					0:  # Varint
						var skip_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
						if skip_result["size"] == -1:
							return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
						offset += skip_result["size"]
					1:  # Fixed64
						offset += 8
					2:  # Length-delimited
						var skip_length_result: Dictionary[String, int] = ProtoCoreUtils.decode_varint(data, offset)
						if skip_length_result["size"] == -1:
							return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
						offset += skip_length_result["size"] + skip_length_result["value"]
					5:  # Fixed32
						offset += 4
					_:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func to_text(indent_level: int = 0) -> String:
	"""Serialize message to protobuf text format."""
	var result: String = ""
	var indent: String = "\t".repeat(indent_level)

	# Repeated field players
	for item in _players:
		result += indent + "players {\n"
		result += item.to_text(indent_level + 1)
		result += indent + "}\n"

	# Field timestamp
	if _timestamp != 0:
		result += indent + "timestamp: " + str(_timestamp) + "\n"

	# Field map_name
	if _map_name != "":
		result += indent + "map_name: \"" + ProtoCoreUtils.escape_string_text_format(_map_name) + "\"\n"

	return result

func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from protobuf text format."""
	var pos: int = 0

	while pos < text.length():
		# Skip whitespace and comments
		pos = ProtoCoreUtils.skip_whitespace(text, pos)
		if pos >= text.length():
			break

		# Parse field name
		var name_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_identifier(text, pos)
		if "error" in name_result:
			push_error(name_result["error"])
			return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
		var field_name: String = name_result["value"]
		pos = name_result["pos"]

		# Skip whitespace before colon
		pos = ProtoCoreUtils.skip_whitespace(text, pos)

		# Match field name and parse value
		match field_name:
			"players":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				# Parse message
				if pos < text.length() and text[pos] == "{":
					pos = pos + 1  # Skip opening brace
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					# Extract message body
					var msg_start: int = pos
					var depth: int = 1
					while pos < text.length() and depth > 0:
						if text[pos] == "{":
							depth = depth + 1
						elif text[pos] == "}":
							depth = depth - 1
							if depth == 0:
								break
						pos = pos + 1

					var msg_text: String = text.substr(msg_start, pos - msg_start)
					pos = pos + 1  # Skip closing brace

					var msg_instance: ExamplePlayer = ExamplePlayer.new()
					var parse_result: ProtoCoreUtils.ProtobufError = msg_instance.from_text(msg_text)
					if parse_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
						return parse_result
					_players.append(msg_instance)
			"timestamp":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var num_result: ProtoCoreUtils.NumberParseResult = ProtoCoreUtils.parse_number(text, pos)
				if num_result.has_error():
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_timestamp = num_result.int_value
				pos = num_result.pos
			"map_name":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var str_result: Dictionary[String, Variant] = ProtoCoreUtils.parse_string_literal(text, pos)
				if "error" in str_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_map_name = str_result["value"]
				pos = str_result["pos"]
			_:
				# Unknown field - skip it
				push_warning("Unknown field: " + field_name)
				# Try to skip the value
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "{":
						# Skip message body
						var depth: int = 1
						pos = pos + 1
						while pos < text.length() and depth > 0:
							if text[pos] == "{":
								depth = depth + 1
							elif text[pos] == "}":
								depth = depth - 1
							pos = pos + 1
					else:
						# Skip to next field
						while pos < text.length() and text[pos] not in ["\n", "#"]:
							pos = pos + 1

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func _to_string() -> String:
	"""Generate debug string representation."""
	var parts: Array[String] = []

	if _players.size() > 0:
		parts.append("players: " + str(_players))
	if _timestamp != 0:
		parts.append("timestamp: " + str(_timestamp))
	if _map_name != "":
		parts.append("map_name: " + str(_map_name))

	return "GameState { " + ", ".join(parts) + " }"
