class_name ExamplePlayerPosition

extends RefCounted

# Generated by gdproto
# Source: example.proto
# DO NOT EDIT

# Fields
var _x: float = 0.0
var _y: float = 0.0
var _z: float = 0.0

# Accessors

func set_x(value: float) -> void:
	_x = value

func get_x() -> float:
	return _x

func set_y(value: float) -> void:
	_y = value

func get_y() -> float:
	return _y

func set_z(value: float) -> void:
	_z = value

func get_z() -> float:
	return _z

# Serialization

func to_bytes() -> PackedByteArray:
	"""Serialize message to bytes."""
	var result: PackedByteArray = PackedByteArray()
	# Field x
	if _x != 0.0:
		result.append_array(ProtoCoreUtils.encode_varint(13))
		result.append_array(ProtoCoreUtils.encode_float(_x))
	# Field y
	if _y != 0.0:
		result.append_array(ProtoCoreUtils.encode_varint(21))
		result.append_array(ProtoCoreUtils.encode_float(_y))
	# Field z
	if _z != 0.0:
		result.append_array(ProtoCoreUtils.encode_varint(29))
		result.append_array(ProtoCoreUtils.encode_float(_z))
	return result

func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from bytes."""
	var offset: int = 0

	while offset < data.size():
		# Read field tag
		var tag_result := ProtoCoreUtils.decode_varint(data, offset)
		if tag_result.size == -1:
			return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
		var tag: int = tag_result.value
		offset += tag_result.size

		var field_number: int = ProtoCoreUtils.get_field_number(tag)
		var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

		match field_number:
			1:
				# Field x
				if offset + 4 > data.size():
					return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
				_x = ProtoCoreUtils.decode_float(data, offset)
				offset += 4
			2:
				# Field y
				if offset + 4 > data.size():
					return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
				_y = ProtoCoreUtils.decode_float(data, offset)
				offset += 4
			3:
				# Field z
				if offset + 4 > data.size():
					return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
				_z = ProtoCoreUtils.decode_float(data, offset)
				offset += 4
			_:
				# Skip unknown field
				match wire_type:
					0:  # Varint
						var skip_result := ProtoCoreUtils.decode_varint(data, offset)
						if skip_result.size == -1:
							return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
						offset += skip_result.size
					1:  # Fixed64
						offset += 8
					2:  # Length-delimited
						var skip_length_result := ProtoCoreUtils.decode_varint(data, offset)
						if skip_length_result.size == -1:
							return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
						offset += skip_length_result.size + skip_length_result.value
					5:  # Fixed32
						offset += 4
					_:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func to_text(indent_level: int = 0) -> String:
	"""Serialize message to protobuf text format."""
	var result: String = ""
	var indent: String = "\t".repeat(indent_level)

	# Field x
	if _x != 0.0:
		if is_inf(_x):
			result += indent + "x: " + ("inf" if _x > 0 else "-inf") + "\n"
		elif is_nan(_x):
			result += indent + "x: nan\n"
		else:
			result += indent + "x: " + str(_x) + "\n"

	# Field y
	if _y != 0.0:
		if is_inf(_y):
			result += indent + "y: " + ("inf" if _y > 0 else "-inf") + "\n"
		elif is_nan(_y):
			result += indent + "y: nan\n"
		else:
			result += indent + "y: " + str(_y) + "\n"

	# Field z
	if _z != 0.0:
		if is_inf(_z):
			result += indent + "z: " + ("inf" if _z > 0 else "-inf") + "\n"
		elif is_nan(_z):
			result += indent + "z: nan\n"
		else:
			result += indent + "z: " + str(_z) + "\n"

	return result

func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
	"""Deserialize message from protobuf text format."""
	var pos: int = 0

	while pos < text.length():
		# Skip whitespace and comments
		pos = ProtoCoreUtils.skip_whitespace(text, pos)
		if pos >= text.length():
			break

		# Parse field name
		var name_result := ProtoCoreUtils.parse_identifier(text, pos)
		if "error" in name_result:
			push_error(name_result["error"])
			return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
		var field_name: String = name_result["value"]
		pos = name_result["pos"]

		# Skip whitespace before colon
		pos = ProtoCoreUtils.skip_whitespace(text, pos)

		# Match field name and parse value
		match field_name:
			"x":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var float_result: Dictionary
				# Check for special values or identifiers
				if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
					var id_result := ProtoCoreUtils.parse_identifier(text, pos)
					if "value" in id_result:
						match id_result["value"]:
							"inf":
								float_result = {"value": INF, "pos": id_result["pos"]}
							"nan":
								float_result = {"value": NAN, "pos": id_result["pos"]}
							_:
								float_result = ProtoCoreUtils.parse_number(text, pos)
					else:
						float_result = ProtoCoreUtils.parse_number(text, pos)
				else:
					float_result = ProtoCoreUtils.parse_number(text, pos)
				if "error" in float_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_x = float(float_result["value"])
				pos = float_result["pos"]
			"y":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var float_result: Dictionary
				# Check for special values or identifiers
				if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
					var id_result := ProtoCoreUtils.parse_identifier(text, pos)
					if "value" in id_result:
						match id_result["value"]:
							"inf":
								float_result = {"value": INF, "pos": id_result["pos"]}
							"nan":
								float_result = {"value": NAN, "pos": id_result["pos"]}
							_:
								float_result = ProtoCoreUtils.parse_number(text, pos)
					else:
						float_result = ProtoCoreUtils.parse_number(text, pos)
				else:
					float_result = ProtoCoreUtils.parse_number(text, pos)
				if "error" in float_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_y = float(float_result["value"])
				pos = float_result["pos"]
			"z":
				# Parse colon
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				var float_result: Dictionary
				# Check for special values or identifiers
				if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
					var id_result := ProtoCoreUtils.parse_identifier(text, pos)
					if "value" in id_result:
						match id_result["value"]:
							"inf":
								float_result = {"value": INF, "pos": id_result["pos"]}
							"nan":
								float_result = {"value": NAN, "pos": id_result["pos"]}
							_:
								float_result = ProtoCoreUtils.parse_number(text, pos)
					else:
						float_result = ProtoCoreUtils.parse_number(text, pos)
				else:
					float_result = ProtoCoreUtils.parse_number(text, pos)
				if "error" in float_result:
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				_z = float(float_result["value"])
				pos = float_result["pos"]
			_:
				# Unknown field - skip it
				push_warning("Unknown field: " + field_name)
				# Try to skip the value
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos < text.length() and text[pos] == ":":
					pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "{":
						# Skip message body
						var depth := 1
						pos = pos + 1
						while pos < text.length() and depth > 0:
							if text[pos] == "{":
								depth = depth + 1
							elif text[pos] == "}":
								depth = depth - 1
							pos = pos + 1
					else:
						# Skip to next field
						while pos < text.length() and text[pos] not in ["\n", "#"]:
							pos = pos + 1

	return ProtoCoreUtils.ProtobufError.NO_ERRORS

func _to_string() -> String:
	"""Generate debug string representation."""
	var parts: Array[String] = []

	if _x != 0.0:
		parts.append("x: " + str(_x))
	if _y != 0.0:
		parts.append("y: " + str(_y))
	if _z != 0.0:
		parts.append("z: " + str(_z))

	return "Position { " + ", ".join(parts) + " }"
