# Generated by gdproto
# Source: example.proto
# DO NOT EDIT


extends RefCounted

# ============================================================================
# Constants
# ============================================================================
const PROTO_VERSION: int = 3

enum PB_ERR {
	NO_ERRORS = 0,
	VARINT_NOT_FOUND = -1,
	REPEATED_COUNT_NOT_FOUND = -2,
	REPEATED_COUNT_MISMATCH = -3,
	LENGTH_DELIMITED_SIZE_NOT_FOUND = -4,
	LENGTH_DELIMITED_SIZE_MISMATCH = -5,
	PACKAGE_SIZE_MISMATCH = -6,
	UNDEFINED_STATE = -7,
	PARSE_INCOMPLETE = -8,
	REQUIRED_FIELDS = -9,
}

# ============================================================================
# Enums
# ============================================================================

enum PlayerStatus {
	OFFLINE = 0,
	ONLINE = 1,
	AWAY = 2,
	IN_GAME = 3,
}

# ============================================================================
# Messages
# ============================================================================

class Player extends RefCounted:
	# Nested message
	class Position extends RefCounted:
		# Fields
		var _x: float = 0.0
		var _y: float = 0.0
		var _z: float = 0.0

		# Accessors
		func set_x(value: float) -> void:
			_x = value
		func get_x() -> float:
			return _x

		func set_y(value: float) -> void:
			_y = value
		func get_y() -> float:
			return _y

		func set_z(value: float) -> void:
			_z = value
		func get_z() -> float:
			return _z


		# Serialization
		func to_bytes() -> PackedByteArray:
			"""Serialize message to bytes."""
			var result: PackedByteArray = PackedByteArray()

			# Field x
			if _x != 0.0:
				result.append_array(PBCore.encode_varint(13))
				result.append_array(PBCore.encode_float(_x))

			# Field y
			if _y != 0.0:
				result.append_array(PBCore.encode_varint(21))
				result.append_array(PBCore.encode_float(_y))

			# Field z
			if _z != 0.0:
				result.append_array(PBCore.encode_varint(29))
				result.append_array(PBCore.encode_float(_z))


			return result

		func from_bytes(data: PackedByteArray) -> int:
			"""Deserialize message from bytes."""
			var offset: int = 0

			while offset < data.size():
				# Read field tag
				var tag_result: Dictionary = PBCore.decode_varint(data, offset)
				if tag_result.size == -1:
					return PB_ERR.VARINT_NOT_FOUND
				var tag: int = tag_result.value
				offset += tag_result.size

				var field_number: int = PBCore.get_field_number(tag)
				var wire_type: int = PBCore.get_wire_type(tag)

				match field_number:
					1:
						# Field x
						if offset + 4 > data.size():
							return PB_ERR.PARSE_INCOMPLETE
						_x = PBCore.decode_float(data, offset)
						offset += 4
					2:
						# Field y
						if offset + 4 > data.size():
							return PB_ERR.PARSE_INCOMPLETE
						_y = PBCore.decode_float(data, offset)
						offset += 4
					3:
						# Field z
						if offset + 4 > data.size():
							return PB_ERR.PARSE_INCOMPLETE
						_z = PBCore.decode_float(data, offset)
						offset += 4
					_:
						# Skip unknown field
						match wire_type:
							0:  # Varint
								var skip_result = PBCore.decode_varint(data, offset)
								if skip_result.size == -1:
									return PB_ERR.VARINT_NOT_FOUND
								offset += skip_result.size
							1:  # Fixed64
								offset += 8
							2:  # Length-delimited
								var skip_length_result = PBCore.decode_varint(data, offset)
								if skip_length_result.size == -1:
									return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
								offset += skip_length_result.size + skip_length_result.value
							5:  # Fixed32
								offset += 4
							_:
								return PB_ERR.UNDEFINED_STATE

			return PB_ERR.NO_ERRORS

		func to_string() -> String:
			"""Generate debug string representation."""
			var parts: Array[String] = []

			if _x != 0.0:
				parts.append("x: " + str(_x))
			if _y != 0.0:
				parts.append("y: " + str(_y))
			if _z != 0.0:
				parts.append("z: " + str(_z))

			return "Position { " + ", ".join(parts) + " }"

	# Fields
	var _username: String = ""
	var _level: int = 0
	var _experience: int = 0
	var _status: PlayerStatus = null
	var _inventory: Array[String] = []
	var _position: Position = null
	var _email: String = ""
	var _discord: String = ""
	var _stats: Dictionary[String, int] = {}

	# Oneof tracking
	var _oneof_contact: String = ""

	# Accessors
	func set_username(value: String) -> void:
		_username = value
	func get_username() -> String:
		return _username

	func set_level(value: int) -> void:
		_level = value
	func get_level() -> int:
		return _level

	func set_experience(value: int) -> void:
		_experience = value
	func get_experience() -> int:
		return _experience

	func new_status() -> PlayerStatus:
		_status = PlayerStatus.new()
		return _status
	func get_status() -> PlayerStatus:
		return _status

	func add_inventory(value: String) -> void:
		_inventory.append(value)
	func get_inventory() -> Array[String]:
		return _inventory

	func new_position() -> Position:
		_position = Position.new()
		return _position
	func get_position() -> Position:
		return _position

	func set_email(value: String) -> void:
		if _oneof_contact != "email":
			_oneof_contact = "email"
		_email = value
	func get_email() -> String:
		return _email
	func has_email() -> bool:
		return _oneof_contact == "email"

	func set_discord(value: String) -> void:
		if _oneof_contact != "discord":
			_oneof_contact = "discord"
		_discord = value
	func get_discord() -> String:
		return _discord
	func has_discord() -> bool:
		return _oneof_contact == "discord"

	func add_stats(key: String, value: int) -> void:
		_stats[key] = value
	func get_stats() -> Dictionary[String, int]:
		return _stats


	# Serialization
	func to_bytes() -> PackedByteArray:
		"""Serialize message to bytes."""
		var result: PackedByteArray = PackedByteArray()

		# Field username
		if _username != "":
			result.append_array(PBCore.encode_varint(10))
			var str_data: PackedByteArray = PBCore.encode_string(_username)
			result.append_array(PBCore.encode_varint(str_data.size()))
			result.append_array(str_data)

		# Field level
		if _level != 0:
			result.append_array(PBCore.encode_varint(16))
			result.append_array(PBCore.encode_varint(_level))

		# Field experience
		if _experience != 0:
			result.append_array(PBCore.encode_varint(24))
			result.append_array(PBCore.encode_varint(_experience))

		# Field status
		if _status != null:
			result.append_array(PBCore.encode_varint(34))
			var msg_data: PackedByteArray = _status.to_bytes()
			result.append_array(PBCore.encode_varint(msg_data.size()))
			result.append_array(msg_data)

		# Field inventory (repeated)
		for item in _inventory:
			result.append_array(PBCore.encode_varint(42))
			var str_data: PackedByteArray = PBCore.encode_string(item)
			result.append_array(PBCore.encode_varint(str_data.size()))
			result.append_array(str_data)

		# Field position
		if _position != null:
			result.append_array(PBCore.encode_varint(58))
			var msg_data: PackedByteArray = _position.to_bytes()
			result.append_array(PBCore.encode_varint(msg_data.size()))
			result.append_array(msg_data)

		# Field email
		if _email != "":
			result.append_array(PBCore.encode_varint(66))
			var str_data: PackedByteArray = PBCore.encode_string(_email)
			result.append_array(PBCore.encode_varint(str_data.size()))
			result.append_array(str_data)

		# Field discord
		if _discord != "":
			result.append_array(PBCore.encode_varint(74))
			var str_data: PackedByteArray = PBCore.encode_string(_discord)
			result.append_array(PBCore.encode_varint(str_data.size()))
			result.append_array(str_data)

		# Map field stats
		for key in _stats:
			var value = _stats[key]

			# Build map entry
			var entry: PackedByteArray = PackedByteArray()

			# Entry field 1: key
			entry.append_array(PBCore.encode_varint(10))
			var key_data: PackedByteArray = PBCore.encode_string(key)
			entry.append_array(PBCore.encode_varint(key_data.size()))
			entry.append_array(key_data)

			# Entry field 2: value
			entry.append_array(PBCore.encode_varint(16))
			entry.append_array(PBCore.encode_varint(value))

			# Append entry to result
			result.append_array(PBCore.encode_varint(50))
			result.append_array(PBCore.encode_varint(entry.size()))
			result.append_array(entry)


		return result

	func from_bytes(data: PackedByteArray) -> int:
		"""Deserialize message from bytes."""
		var offset: int = 0

		while offset < data.size():
			# Read field tag
			var tag_result: Dictionary = PBCore.decode_varint(data, offset)
			if tag_result.size == -1:
				return PB_ERR.VARINT_NOT_FOUND
			var tag: int = tag_result.value
			offset += tag_result.size

			var field_number: int = PBCore.get_field_number(tag)
			var wire_type: int = PBCore.get_wire_type(tag)

			match field_number:
				1:
					# Field username
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					_username = PBCore.decode_string(data, offset, length)
					offset += length
				2:
					# Field level
					var result = PBCore.decode_varint(data, offset)
					if result.size == -1:
						return PB_ERR.VARINT_NOT_FOUND
					_level = result.value
					offset += result.size
				3:
					# Field experience
					var result = PBCore.decode_varint(data, offset)
					if result.size == -1:
						return PB_ERR.VARINT_NOT_FOUND
					_experience = result.value
					offset += result.size
				4:
					# Field status
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					var msg_data: PackedByteArray = data.slice(offset, offset + length)
					_status = PlayerStatus.new()
					var msg_result = _status.from_bytes(msg_data)
					if msg_result != PB_ERR.NO_ERRORS:
						return msg_result
					offset += length
				5:
					# Field inventory
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					_inventory.append(PBCore.decode_string(data, offset, length))
					offset += length
				7:
					# Field position
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					var msg_data: PackedByteArray = data.slice(offset, offset + length)
					_position = Position.new()
					var msg_result = _position.from_bytes(msg_data)
					if msg_result != PB_ERR.NO_ERRORS:
						return msg_result
					offset += length
				6:
					# Map field stats
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH

					var entry_data: PackedByteArray = data.slice(offset, offset + length)
					var entry_offset: int = 0

					var map_key = ""
					var map_value = 0

					while entry_offset < entry_data.size():
						var entry_tag_result = PBCore.decode_varint(entry_data, entry_offset)
						if entry_tag_result.size == -1:
							return PB_ERR.VARINT_NOT_FOUND
						var entry_tag: int = entry_tag_result.value
						entry_offset += entry_tag_result.size
						var entry_field_number: int = PBCore.get_field_number(entry_tag)

						match entry_field_number:
							1:
								# Entry key
								var len_result = PBCore.decode_varint(entry_data, entry_offset)
								if len_result.size == -1:
									return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
								entry_offset += len_result.size
								var str_len: int = len_result.value
								if entry_offset + str_len > entry_data.size():
									return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
								map_key = PBCore.decode_string(entry_data, entry_offset, str_len)
								entry_offset += str_len
							2:
								# Entry value
								var result = PBCore.decode_varint(entry_data, entry_offset)
								if result.size == -1:
									return PB_ERR.VARINT_NOT_FOUND
								map_value = result.value
								entry_offset += result.size

					_stats[map_key] = map_value
					offset += length
				_:
					# Skip unknown field
					match wire_type:
						0:  # Varint
							var skip_result = PBCore.decode_varint(data, offset)
							if skip_result.size == -1:
								return PB_ERR.VARINT_NOT_FOUND
							offset += skip_result.size
						1:  # Fixed64
							offset += 8
						2:  # Length-delimited
							var skip_length_result = PBCore.decode_varint(data, offset)
							if skip_length_result.size == -1:
								return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
							offset += skip_length_result.size + skip_length_result.value
						5:  # Fixed32
							offset += 4
						_:
							return PB_ERR.UNDEFINED_STATE

		return PB_ERR.NO_ERRORS

	func to_string() -> String:
		"""Generate debug string representation."""
		var parts: Array[String] = []

		if _username != "":
			parts.append("username: " + str(_username))
		if _level != 0:
			parts.append("level: " + str(_level))
		if _experience != 0:
			parts.append("experience: " + str(_experience))
		if _status != null:
			parts.append("status: " + _status.to_string())
		if _inventory.size() > 0:
			parts.append("inventory: " + str(_inventory))
		if _position != null:
			parts.append("position: " + _position.to_string())
		if _email != "":
			parts.append("email: " + str(_email))
		if _discord != "":
			parts.append("discord: " + str(_discord))

		return "Player { " + ", ".join(parts) + " }"

class GameState extends RefCounted:
	# Fields
	var _players: Array[Player] = []
	var _timestamp: int = 0
	var _map_name: String = ""

	# Accessors
	func add_players() -> Player:
		var item: Player = Player.new()
		_players.append(item)
		return item
	func get_players() -> Array[Player]:
		return _players

	func set_timestamp(value: int) -> void:
		_timestamp = value
	func get_timestamp() -> int:
		return _timestamp

	func set_map_name(value: String) -> void:
		_map_name = value
	func get_map_name() -> String:
		return _map_name


	# Serialization
	func to_bytes() -> PackedByteArray:
		"""Serialize message to bytes."""
		var result: PackedByteArray = PackedByteArray()

		# Field players (repeated)
		for item in _players:
			result.append_array(PBCore.encode_varint(10))
			var msg_data: PackedByteArray = item.to_bytes()
			result.append_array(PBCore.encode_varint(msg_data.size()))
			result.append_array(msg_data)

		# Field timestamp
		if _timestamp != 0:
			result.append_array(PBCore.encode_varint(16))
			result.append_array(PBCore.encode_varint(_timestamp))

		# Field map_name
		if _map_name != "":
			result.append_array(PBCore.encode_varint(26))
			var str_data: PackedByteArray = PBCore.encode_string(_map_name)
			result.append_array(PBCore.encode_varint(str_data.size()))
			result.append_array(str_data)


		return result

	func from_bytes(data: PackedByteArray) -> int:
		"""Deserialize message from bytes."""
		var offset: int = 0

		while offset < data.size():
			# Read field tag
			var tag_result: Dictionary = PBCore.decode_varint(data, offset)
			if tag_result.size == -1:
				return PB_ERR.VARINT_NOT_FOUND
			var tag: int = tag_result.value
			offset += tag_result.size

			var field_number: int = PBCore.get_field_number(tag)
			var wire_type: int = PBCore.get_wire_type(tag)

			match field_number:
				1:
					# Field players
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					var msg_data: PackedByteArray = data.slice(offset, offset + length)
					var msg_item = Player.new()
					var msg_result = msg_item.from_bytes(msg_data)
					if msg_result != PB_ERR.NO_ERRORS:
						return msg_result
					_players.append(msg_item)
					offset += length
				2:
					# Field timestamp
					var result = PBCore.decode_varint(data, offset)
					if result.size == -1:
						return PB_ERR.VARINT_NOT_FOUND
					_timestamp = result.value
					offset += result.size
				3:
					# Field map_name
					var length_result = PBCore.decode_varint(data, offset)
					if length_result.size == -1:
						return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return PB_ERR.LENGTH_DELIMITED_SIZE_MISMATCH
					_map_name = PBCore.decode_string(data, offset, length)
					offset += length
				_:
					# Skip unknown field
					match wire_type:
						0:  # Varint
							var skip_result = PBCore.decode_varint(data, offset)
							if skip_result.size == -1:
								return PB_ERR.VARINT_NOT_FOUND
							offset += skip_result.size
						1:  # Fixed64
							offset += 8
						2:  # Length-delimited
							var skip_length_result = PBCore.decode_varint(data, offset)
							if skip_length_result.size == -1:
								return PB_ERR.LENGTH_DELIMITED_SIZE_NOT_FOUND
							offset += skip_length_result.size + skip_length_result.value
						5:  # Fixed32
							offset += 4
						_:
							return PB_ERR.UNDEFINED_STATE

		return PB_ERR.NO_ERRORS

	func to_string() -> String:
		"""Generate debug string representation."""
		var parts: Array[String] = []

		if _players.size() > 0:
			parts.append("players: " + str(_players))
		if _timestamp != 0:
			parts.append("timestamp: " + str(_timestamp))
		if _map_name != "":
			parts.append("map_name: " + str(_map_name))

		return "GameState { " + ", ".join(parts) + " }"

# ============================================================================
# Protobuf Core (Serialization utilities)
# ============================================================================

class PBCore:
	"""Core protobuf encoding/decoding utilities."""
	
	# Encode/decode varint (variable-length integer)
	static func encode_varint(value: int) -> PackedByteArray:
		"""Encode integer as varint."""
		var result: PackedByteArray = PackedByteArray()
		while value > 0x7F:
			result.append((value & 0x7F) | 0x80)
			value >>= 7
		result.append(value & 0x7F)
		return result
	
	static func decode_varint(data: PackedByteArray, offset: int) -> Dictionary[String, int]:
		"""Decode varint from data.
		
		Returns:
			Dictionary with 'value' and 'size' keys
		"""
		var result: int = 0
		var shift: int = 0
		var size: int = 0
		
		while offset + size < data.size():
			var byte: int = data[offset + size]
			result |= (byte & 0x7F) << shift
			size += 1
			if (byte & 0x80) == 0:
				return {"value": result, "size": size}
			shift += 7
			if shift > 63:
				break
		
		return {"value": 0, "size": -1}
	
	# Encode/decode zigzag (for sint32/sint64)
	static func encode_zigzag32(value: int) -> int:
		"""Encode signed int32 using zigzag encoding."""
		return (value << 1) ^ (value >> 31)
	
	static func encode_zigzag64(value: int) -> int:
		"""Encode signed int64 using zigzag encoding."""
		return (value << 1) ^ (value >> 63)
	
	static func decode_zigzag32(value: int) -> int:
		"""Decode zigzag-encoded int32."""
		return (value >> 1) ^ (-(value & 1))
	
	static func decode_zigzag64(value: int) -> int:
		"""Decode zigzag-encoded int64."""
		return (value >> 1) ^ (-(value & 1))
	
	# Encode/decode fixed-size integers
	static func encode_fixed32(value: int) -> PackedByteArray:
		"""Encode 32-bit fixed integer."""
		var result: PackedByteArray = PackedByteArray()
		result.resize(4)
		result.encode_u32(0, value)
		return result
	
	static func encode_fixed64(value: int) -> PackedByteArray:
		"""Encode 64-bit fixed integer."""
		var result: PackedByteArray = PackedByteArray()
		result.resize(8)
		result.encode_u64(0, value)
		return result
	
	static func decode_fixed32(data: PackedByteArray, offset: int) -> int:
		"""Decode 32-bit fixed integer."""
		return data.decode_u32(offset)
	
	static func decode_fixed64(data: PackedByteArray, offset: int) -> int:
		"""Decode 64-bit fixed integer."""
		return data.decode_u64(offset)
	
	# Encode/decode float/double
	static func encode_float(value: float) -> PackedByteArray:
		"""Encode 32-bit float."""
		var result: PackedByteArray = PackedByteArray()
		result.resize(4)
		result.encode_float(0, value)
		return result
	
	static func encode_double(value: float) -> PackedByteArray:
		"""Encode 64-bit double."""
		var result: PackedByteArray = PackedByteArray()
		result.resize(8)
		result.encode_double(0, value)
		return result
	
	static func decode_float(data: PackedByteArray, offset: int) -> float:
		"""Decode 32-bit float."""
		return data.decode_float(offset)
	
	static func decode_double(data: PackedByteArray, offset: int) -> float:
		"""Decode 64-bit double."""
		return data.decode_double(offset)
	
	# Encode/decode string
	static func encode_string(value: String) -> PackedByteArray:
		"""Encode string as UTF-8."""
		return value.to_utf8_buffer()
	
	static func decode_string(data: PackedByteArray, offset: int, length: int) -> String:
		"""Decode UTF-8 string."""
		var slice: PackedByteArray = data.slice(offset, offset + length)
		return slice.get_string_from_utf8()
	
	# Make field tag
	static func make_tag(field_number: int, wire_type: int) -> int:
		"""Make protobuf field tag."""
		return (field_number << 3) | wire_type
	
	# Get wire type from tag
	static func get_wire_type(tag: int) -> int:
		"""Extract wire type from tag."""
		return tag & 0x7
	
	# Get field number from tag
	static func get_field_number(tag: int) -> int:
		"""Extract field number from tag."""
		return tag >> 3
