class_name ExampleProto

extends RefCounted

# Generated by gdproto
# Source: example.proto
# DO NOT EDIT



enum PlayerStatus {
	OFFLINE = 0,
	ONLINE = 1,
	AWAY = 2,
	IN_GAME = 3
}



class Player extends RefCounted:
	# Nested message

	class Position extends RefCounted:
		# Fields

		var _x: float = 0.0

		var _y: float = 0.0

		var _z: float = 0.0



		# Accessors

		func set_x(value: float) -> void:
			_x = value

		func get_x() -> float:
			return _x



		func set_y(value: float) -> void:
			_y = value

		func get_y() -> float:
			return _y



		func set_z(value: float) -> void:
			_z = value

		func get_z() -> float:
			return _z





		# Serialization

		func to_bytes() -> PackedByteArray:
			"""Serialize message to bytes."""
			var result: PackedByteArray = PackedByteArray()
			# Field x
			if _x != 0.0:
				result.append_array(ProtoCoreUtils.encode_varint(13))
				result.append_array(ProtoCoreUtils.encode_float(_x))
			# Field y
			if _y != 0.0:
				result.append_array(ProtoCoreUtils.encode_varint(21))
				result.append_array(ProtoCoreUtils.encode_float(_y))
			# Field z
			if _z != 0.0:
				result.append_array(ProtoCoreUtils.encode_varint(29))
				result.append_array(ProtoCoreUtils.encode_float(_z))
			return result



		func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
			"""Deserialize message from bytes."""
			var offset: int = 0

			while offset < data.size():
				# Read field tag
				var tag_result := ProtoCoreUtils.decode_varint(data, offset)
				if tag_result.size == -1:
					return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
				var tag: int = tag_result.value
				offset += tag_result.size

				var field_number: int = ProtoCoreUtils.get_field_number(tag)
				var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

				match field_number:
					1:
						# Field x
						if offset + 4 > data.size():
							return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
						_x = ProtoCoreUtils.decode_float(data, offset)
						offset += 4
					2:
						# Field y
						if offset + 4 > data.size():
							return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
						_y = ProtoCoreUtils.decode_float(data, offset)
						offset += 4
					3:
						# Field z
						if offset + 4 > data.size():
							return ProtoCoreUtils.ProtobufError.PARSE_INCOMPLETE
						_z = ProtoCoreUtils.decode_float(data, offset)
						offset += 4
					_:
						# Skip unknown field
						match wire_type:
							0:  # Varint
								var skip_result := ProtoCoreUtils.decode_varint(data, offset)
								if skip_result.size == -1:
									return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
								offset += skip_result.size
							1:  # Fixed64
								offset += 8
							2:  # Length-delimited
								var skip_length_result := ProtoCoreUtils.decode_varint(data, offset)
								if skip_length_result.size == -1:
									return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
								offset += skip_length_result.size + skip_length_result.value
							5:  # Fixed32
								offset += 4
							_:
								return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

			return ProtoCoreUtils.ProtobufError.NO_ERRORS



		func to_text(indent_level: int = 0) -> String:
			"""Serialize message to protobuf text format."""
			var result: String = ""
			var indent: String = "\t".repeat(indent_level)

			# Field x
			if _x != 0.0:
				if is_inf(_x):
					result += indent + "x: " + ("inf" if _x > 0 else "-inf") + "\n"
				elif is_nan(_x):
					result += indent + "x: nan\n"
				else:
					result += indent + "x: " + str(_x) + "\n"

			# Field y
			if _y != 0.0:
				if is_inf(_y):
					result += indent + "y: " + ("inf" if _y > 0 else "-inf") + "\n"
				elif is_nan(_y):
					result += indent + "y: nan\n"
				else:
					result += indent + "y: " + str(_y) + "\n"

			# Field z
			if _z != 0.0:
				if is_inf(_z):
					result += indent + "z: " + ("inf" if _z > 0 else "-inf") + "\n"
				elif is_nan(_z):
					result += indent + "z: nan\n"
				else:
					result += indent + "z: " + str(_z) + "\n"

			return result



		func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
			"""Deserialize message from protobuf text format."""
			var pos: int = 0

			while pos < text.length():
				# Skip whitespace and comments
				pos = ProtoCoreUtils.skip_whitespace(text, pos)
				if pos >= text.length():
					break

				# Parse field name
				var name_result := ProtoCoreUtils.parse_identifier(text, pos)
				if "error" in name_result:
					push_error(name_result["error"])
					return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
				var field_name: String = name_result["value"]
				pos = name_result["pos"]

				# Skip whitespace before colon
				pos = ProtoCoreUtils.skip_whitespace(text, pos)

				# Match field name and parse value
				match field_name:
					"x":
						# Parse colon
						if pos < text.length() and text[pos] == ":":
							pos = pos + 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						var float_result: Dictionary
						# Check for special values or identifiers
						if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
							var id_result := ProtoCoreUtils.parse_identifier(text, pos)
							if "value" in id_result:
								match id_result["value"]:
									"inf":
										float_result = {"value": INF, "pos": id_result["pos"]}
									"nan":
										float_result = {"value": NAN, "pos": id_result["pos"]}
									_:
										float_result = ProtoCoreUtils.parse_number(text, pos)
							else:
								float_result = ProtoCoreUtils.parse_number(text, pos)
						else:
							float_result = ProtoCoreUtils.parse_number(text, pos)
						if "error" in float_result:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
						_x = float(float_result["value"])
						pos = float_result["pos"]
					"y":
						# Parse colon
						if pos < text.length() and text[pos] == ":":
							pos = pos + 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						var float_result: Dictionary
						# Check for special values or identifiers
						if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
							var id_result := ProtoCoreUtils.parse_identifier(text, pos)
							if "value" in id_result:
								match id_result["value"]:
									"inf":
										float_result = {"value": INF, "pos": id_result["pos"]}
									"nan":
										float_result = {"value": NAN, "pos": id_result["pos"]}
									_:
										float_result = ProtoCoreUtils.parse_number(text, pos)
							else:
								float_result = ProtoCoreUtils.parse_number(text, pos)
						else:
							float_result = ProtoCoreUtils.parse_number(text, pos)
						if "error" in float_result:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
						_y = float(float_result["value"])
						pos = float_result["pos"]
					"z":
						# Parse colon
						if pos < text.length() and text[pos] == ":":
							pos = pos + 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						var float_result: Dictionary
						# Check for special values or identifiers
						if pos < text.length() and text[pos] in ["i", "n", "-", "+"] or not text[pos].is_valid_int():
							var id_result := ProtoCoreUtils.parse_identifier(text, pos)
							if "value" in id_result:
								match id_result["value"]:
									"inf":
										float_result = {"value": INF, "pos": id_result["pos"]}
									"nan":
										float_result = {"value": NAN, "pos": id_result["pos"]}
									_:
										float_result = ProtoCoreUtils.parse_number(text, pos)
							else:
								float_result = ProtoCoreUtils.parse_number(text, pos)
						else:
							float_result = ProtoCoreUtils.parse_number(text, pos)
						if "error" in float_result:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
						_z = float(float_result["value"])
						pos = float_result["pos"]
					_:
						# Unknown field - skip it
						push_warning("Unknown field: " + field_name)
						# Try to skip the value
						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == ":":
							pos = pos + 1
							pos = ProtoCoreUtils.skip_whitespace(text, pos)
							if pos < text.length() and text[pos] == "{":
								# Skip message body
								var depth := 1
								pos = pos + 1
								while pos < text.length() and depth > 0:
									if text[pos] == "{":
										depth = depth + 1
									elif text[pos] == "}":
										depth = depth - 1
									pos = pos + 1
							else:
								# Skip to next field
								while pos < text.length() and text[pos] not in ["\n", "#"]:
									pos = pos + 1

			return ProtoCoreUtils.ProtobufError.NO_ERRORS



		func _to_string() -> String:
			"""Generate debug string representation."""
			var parts: Array[String] = []

			if _x != 0.0:
				parts.append("x: " + str(_x))
			if _y != 0.0:
				parts.append("y: " + str(_y))
			if _z != 0.0:
				parts.append("z: " + str(_z))

			return "Position { " + ", ".join(parts) + " }"



	# Fields

	var _username: String = ""

	var _level: int = 0

	var _experience: int = 0

	var _status: PlayerStatus = 0

	var _inventory: Array[String] = []

	var _position: Position = null

	var _email: String = ""

	var _discord: String = ""

	var _stats: Dictionary[String, int] = {}



	# Oneof enums

	enum ContactOneOf {
		UNSET = 0,
		EMAIL = 1,
		DISCORD = 2
	}



	# Oneof tracking

	var _oneof_contact: ContactOneOf = ContactOneOf.UNSET



	# Accessors

	func set_username(value: String) -> void:
		_username = value

	func get_username() -> String:
		return _username



	func set_level(value: int) -> void:
		_level = value

	func get_level() -> int:
		return _level



	func set_experience(value: int) -> void:
		_experience = value

	func get_experience() -> int:
		return _experience



	func set_status(value: PlayerStatus) -> void:
		_status = value

	func get_status() -> PlayerStatus:
		return _status



	func add_inventory(value: String) -> void:
		_inventory.append(value)

	func get_inventory() -> Array[String]:
		return _inventory



	func new_position() -> Position:
		_position = Position.new()
		return _position

	func get_position() -> Position:
		return _position



	func set_email(value: String) -> void:
		if _oneof_contact != ContactOneOf.EMAIL:
			_discord = ""
			_oneof_contact = ContactOneOf.EMAIL
		_email = value

	func get_email() -> String:
		return _email

	func has_email() -> bool:
		return _oneof_contact == ContactOneOf.EMAIL



	func set_discord(value: String) -> void:
		if _oneof_contact != ContactOneOf.DISCORD:
			_email = ""
			_oneof_contact = ContactOneOf.DISCORD
		_discord = value

	func get_discord() -> String:
		return _discord

	func has_discord() -> bool:
		return _oneof_contact == ContactOneOf.DISCORD



	func add_stats(key: String, value: int) -> void:
		_stats[key] = value

	func get_stats() -> Dictionary[String, int]:
		return _stats





	# Oneof case getters

	func get_contact_case() -> ContactOneOf:
		return _oneof_contact



	# Enum name lookup helpers

	func _get_enum_name_status(value: int) -> String:
		"""Get enum name for status value."""
		match value:
			PlayerStatus.OFFLINE:
				return "OFFLINE"
			PlayerStatus.ONLINE:
				return "ONLINE"
			PlayerStatus.AWAY:
				return "AWAY"
			PlayerStatus.IN_GAME:
				return "IN_GAME"
			_:
				return str(value)

	func _parse_enum_value_status(name: String) -> int:
		"""Parse enum value from name for status."""
		match name:
			"OFFLINE":
				return PlayerStatus.OFFLINE
			"ONLINE":
				return PlayerStatus.ONLINE
			"AWAY":
				return PlayerStatus.AWAY
			"IN_GAME":
				return PlayerStatus.IN_GAME
			_:
				return 0



	# Serialization

	func to_bytes() -> PackedByteArray:
		"""Serialize message to bytes."""
		var result: PackedByteArray = PackedByteArray()
		# Field username
		if _username != "":
			result.append_array(ProtoCoreUtils.encode_varint(10))
			var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_username)
			result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
			result.append_array(str_data)
		# Field level
		if _level != 0:
			result.append_array(ProtoCoreUtils.encode_varint(16))
			result.append_array(ProtoCoreUtils.encode_varint(_level))
		# Field experience
		if _experience != 0:
			result.append_array(ProtoCoreUtils.encode_varint(24))
			result.append_array(ProtoCoreUtils.encode_varint(_experience))
		# Field status
		if _status != 0:
			result.append_array(ProtoCoreUtils.encode_varint(34))
			result.append_array(ProtoCoreUtils.encode_varint(_status))
		# Field inventory (repeated)
		for item in _inventory:
			result.append_array(ProtoCoreUtils.encode_varint(42))
			var str_data: PackedByteArray = ProtoCoreUtils.encode_string(item)
			result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
			result.append_array(str_data)
		# Field position
		if _position != null:
			result.append_array(ProtoCoreUtils.encode_varint(58))
			var msg_data: PackedByteArray = _position.to_bytes()
			result.append_array(ProtoCoreUtils.encode_varint(msg_data.size()))
			result.append_array(msg_data)
		# Oneof group contact
		match _oneof_contact:
			ContactOneOf.EMAIL:
				# Field email
				result.append_array(ProtoCoreUtils.encode_varint(66))
				var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_email)
				result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
				result.append_array(str_data)
			ContactOneOf.DISCORD:
				# Field discord
				result.append_array(ProtoCoreUtils.encode_varint(74))
				var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_discord)
				result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
				result.append_array(str_data)
		# Map field stats
		for key in _stats:
			var value := _stats[key]

			# Build map entry
			var entry: PackedByteArray = PackedByteArray()

			# Entry field 1: key
			entry.append_array(ProtoCoreUtils.encode_varint(10))
			var key_data: PackedByteArray = ProtoCoreUtils.encode_string(key)
			entry.append_array(ProtoCoreUtils.encode_varint(key_data.size()))
			entry.append_array(key_data)

			# Entry field 2: value
			entry.append_array(ProtoCoreUtils.encode_varint(16))
			entry.append_array(ProtoCoreUtils.encode_varint(value))

			# Append entry to result
			result.append_array(ProtoCoreUtils.encode_varint(50))
			result.append_array(ProtoCoreUtils.encode_varint(entry.size()))
			result.append_array(entry)
		return result



	func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
		"""Deserialize message from bytes."""
		var offset: int = 0

		while offset < data.size():
			# Read field tag
			var tag_result := ProtoCoreUtils.decode_varint(data, offset)
			if tag_result.size == -1:
				return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
			var tag: int = tag_result.value
			offset += tag_result.size

			var field_number: int = ProtoCoreUtils.get_field_number(tag)
			var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

			match field_number:
				1:
					# Field username
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					_username = ProtoCoreUtils.decode_string(data, offset, length)
					offset += length
				2:
					# Field level
					var result := ProtoCoreUtils.decode_varint(data, offset)
					if result.size == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					_level = result.value
					offset += result.size
				3:
					# Field experience
					var result := ProtoCoreUtils.decode_varint(data, offset)
					if result.size == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					_experience = result.value
					offset += result.size
				4:
					# Field status
					var result := ProtoCoreUtils.decode_varint(data, offset)
					if result.size == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					_status = result.value
					offset += result.size
				5:
					# Field inventory
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					_inventory.append(ProtoCoreUtils.decode_string(data, offset, length))
					offset += length
				7:
					# Field position
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					var msg_data: PackedByteArray = data.slice(offset, offset + length)
					_position = Position.new()
					var msg_result := _position.from_bytes(msg_data)
					if msg_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
						return msg_result
					offset += length
				6:
					# Map field stats
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH

					var entry_data: PackedByteArray = data.slice(offset, offset + length)
					var entry_offset: int = 0

					var map_key := ""
					var map_value := 0

					while entry_offset < entry_data.size():
						var entry_tag_result := ProtoCoreUtils.decode_varint(entry_data, entry_offset)
						if entry_tag_result.size == -1:
							return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
						var entry_tag: int = entry_tag_result.value
						entry_offset += entry_tag_result.size
						var entry_field_number: int = ProtoCoreUtils.get_field_number(entry_tag)

						match entry_field_number:
							1:
								# Entry key
								var len_result := ProtoCoreUtils.decode_varint(entry_data, entry_offset)
								if len_result.size == -1:
									return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
								entry_offset += len_result.size
								var str_len: int = len_result.value
								if entry_offset + str_len > entry_data.size():
									return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
								map_key = ProtoCoreUtils.decode_string(entry_data, entry_offset, str_len)
								entry_offset += str_len
							2:
								# Entry value
								var result := ProtoCoreUtils.decode_varint(entry_data, entry_offset)
								if result.size == -1:
									return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
								map_value = result.value
								entry_offset += result.size

					_stats[map_key] = map_value
					offset += length
				8:
					# Field email
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					_email = ProtoCoreUtils.decode_string(data, offset, length)
					offset += length
					_oneof_contact = ContactOneOf.EMAIL
				9:
					# Field discord
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					_discord = ProtoCoreUtils.decode_string(data, offset, length)
					offset += length
					_oneof_contact = ContactOneOf.DISCORD
				_:
					# Skip unknown field
					match wire_type:
						0:  # Varint
							var skip_result := ProtoCoreUtils.decode_varint(data, offset)
							if skip_result.size == -1:
								return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
							offset += skip_result.size
						1:  # Fixed64
							offset += 8
						2:  # Length-delimited
							var skip_length_result := ProtoCoreUtils.decode_varint(data, offset)
							if skip_length_result.size == -1:
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
							offset += skip_length_result.size + skip_length_result.value
						5:  # Fixed32
							offset += 4
						_:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

		return ProtoCoreUtils.ProtobufError.NO_ERRORS



	func to_text(indent_level: int = 0) -> String:
		"""Serialize message to protobuf text format."""
		var result: String = ""
		var indent: String = "\t".repeat(indent_level)

		# Field username
		if _username != "":
			result += indent + "username: \"" + ProtoCoreUtils.escape_string_text_format(_username) + "\"\n"

		# Field level
		if _level != 0:
			result += indent + "level: " + str(_level) + "\n"

		# Field experience
		if _experience != 0:
			result += indent + "experience: " + str(_experience) + "\n"

		# Field status
		if _status != 0:
			result += indent + "status: " + _get_enum_name_status(_status) + "\n"

		# Repeated field inventory
		for item in _inventory:
			result += indent + "inventory: \"" + ProtoCoreUtils.escape_string_text_format(item) + "\"\n"

		# Field position
		if _position != null:
			result += indent + "position {\n"
			result += _position.to_text(indent_level + 1)
			result += indent + "}\n"

		# Oneof group: contact
		match _oneof_contact:
			ContactOneOf.EMAIL:
				result += indent + "email: \"" + ProtoCoreUtils.escape_string_text_format(_email) + "\"\n"
			ContactOneOf.DISCORD:
				result += indent + "discord: \"" + ProtoCoreUtils.escape_string_text_format(_discord) + "\"\n"

		# Map field stats
		for key in _stats:
			var value := _stats[key]
			result += indent + "stats {\n"
			var inner_indent: String = "\t".repeat(indent_level + 1)

			result += inner_indent + "key: \"" + ProtoCoreUtils.escape_string_text_format(key) + "\"\n"
			result += inner_indent + "value: " + str(value) + "\n"

			result += indent + "}\n"

		return result



	func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
		"""Deserialize message from protobuf text format."""
		var pos: int = 0

		while pos < text.length():
			# Skip whitespace and comments
			pos = ProtoCoreUtils.skip_whitespace(text, pos)
			if pos >= text.length():
				break

			# Parse field name
			var name_result := ProtoCoreUtils.parse_identifier(text, pos)
			if "error" in name_result:
				push_error(name_result["error"])
				return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
			var field_name: String = name_result["value"]
			pos = name_result["pos"]

			# Skip whitespace before colon
			pos = ProtoCoreUtils.skip_whitespace(text, pos)

			# Match field name and parse value
			match field_name:
				"username":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
					if "error" in str_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_username = str_result["value"]
					pos = str_result["pos"]
				"level":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var num_result := ProtoCoreUtils.parse_number(text, pos)
					if "error" in num_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_level = int(num_result["value"])
					pos = num_result["pos"]
				"experience":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var num_result := ProtoCoreUtils.parse_number(text, pos)
					if "error" in num_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_experience = int(num_result["value"])
					pos = num_result["pos"]
				"status":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					# Parse enum value (name or number)
					var enum_result: Dictionary
					if pos < text.length() and not text[pos].is_valid_int() and text[pos] != "-":
						# Parse as identifier (enum name)
						enum_result = ProtoCoreUtils.parse_identifier(text, pos)
						if "error" not in enum_result:
							var enum_name: String = enum_result["value"]
							var enum_value: int = _parse_enum_value_status(enum_name)
							_status = enum_value
							pos = enum_result["pos"]
					else:
						# Parse as number
						enum_result = ProtoCoreUtils.parse_number(text, pos)
						if "error" in enum_result:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
						_status = int(enum_result["value"])
						pos = enum_result["pos"]
				"inventory":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
					if "error" in str_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_inventory.append(str_result["value"])
					pos = str_result["pos"]
				"position":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					# Parse message
					if pos < text.length() and text[pos] == "{":
						pos = pos + 1  # Skip opening brace
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						# Extract message body
						var msg_start := pos
						var depth := 1
						while pos < text.length() and depth > 0:
							if text[pos] == "{":
								depth = depth + 1
							elif text[pos] == "}":
								depth = depth - 1
								if depth == 0:
									break
							pos = pos + 1

						var msg_text := text.substr(msg_start, pos - msg_start)
						pos = pos + 1  # Skip closing brace

						_position = Position.new()
						var parse_result := _position.from_text(msg_text)
						if parse_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
							return parse_result
				"email":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
					if "error" in str_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_email = str_result["value"]
					_oneof_contact = ContactOneOf.EMAIL
					pos = str_result["pos"]
				"discord":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
					if "error" in str_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_discord = str_result["value"]
					_oneof_contact = ContactOneOf.DISCORD
					pos = str_result["pos"]
				"stats":
					# Parse map entry
					if pos < text.length() and text[pos] == ":":
						pos += 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == "{":
						pos += 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						var map_key = null
						var map_value = null

						# Parse key and value
						while pos < text.length() and text[pos] != "}":
							var entry_name_result := ProtoCoreUtils.parse_identifier(text, pos)
							if "error" in entry_name_result:
								break
							var entry_field: String = entry_name_result["value"]
							pos = entry_name_result["pos"]
							pos = ProtoCoreUtils.skip_whitespace(text, pos)
							if pos < text.length() and text[pos] == ":":
								pos += 1
							pos = ProtoCoreUtils.skip_whitespace(text, pos)

							if entry_field == "key":
								var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
								if "value" in str_result:
									map_key = str_result["value"]
									pos = str_result["pos"]
							elif entry_field == "value":
								var num_result := ProtoCoreUtils.parse_number(text, pos)
								if "value" in num_result:
									map_value = int(num_result["value"])
									pos = num_result["pos"]

							pos = ProtoCoreUtils.skip_whitespace(text, pos)

						if map_key != null and map_value != null:
							_stats[map_key] = map_value

						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == "}":
							pos += 1
				_:
					# Unknown field - skip it
					push_warning("Unknown field: " + field_name)
					# Try to skip the value
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == "{":
							# Skip message body
							var depth := 1
							pos = pos + 1
							while pos < text.length() and depth > 0:
								if text[pos] == "{":
									depth = depth + 1
								elif text[pos] == "}":
									depth = depth - 1
								pos = pos + 1
						else:
							# Skip to next field
							while pos < text.length() and text[pos] not in ["\n", "#"]:
								pos = pos + 1

		return ProtoCoreUtils.ProtobufError.NO_ERRORS



	func _to_string() -> String:
		"""Generate debug string representation."""
		var parts: Array[String] = []

		if _username != "":
			parts.append("username: " + str(_username))
		if _level != 0:
			parts.append("level: " + str(_level))
		if _experience != 0:
			parts.append("experience: " + str(_experience))
		if _status != 0:
			parts.append("status: " + str(_status))
		if _inventory.size() > 0:
			parts.append("inventory: " + str(_inventory))
		if _position != null:
			parts.append("position: " + str(_position))
		if _stats.size() > 0:
			parts.append("stats: " + str(_stats))
		if _email != "":
			parts.append("email: " + str(_email))
		if _discord != "":
			parts.append("discord: " + str(_discord))

		return "Player { " + ", ".join(parts) + " }"



class GameState extends RefCounted:
	# Fields

	var _players: Array[Player] = []

	var _timestamp: int = 0

	var _map_name: String = ""



	# Accessors

	func add_players() -> Player:
		var item: Player = Player.new()
		_players.append(item)
		return item

	func get_players() -> Array[Player]:
		return _players



	func set_timestamp(value: int) -> void:
		_timestamp = value

	func get_timestamp() -> int:
		return _timestamp



	func set_map_name(value: String) -> void:
		_map_name = value

	func get_map_name() -> String:
		return _map_name





	# Serialization

	func to_bytes() -> PackedByteArray:
		"""Serialize message to bytes."""
		var result: PackedByteArray = PackedByteArray()
		# Field players (repeated)
		for item in _players:
			result.append_array(ProtoCoreUtils.encode_varint(10))
			var msg_data: PackedByteArray = item.to_bytes()
			result.append_array(ProtoCoreUtils.encode_varint(msg_data.size()))
			result.append_array(msg_data)
		# Field timestamp
		if _timestamp != 0:
			result.append_array(ProtoCoreUtils.encode_varint(16))
			result.append_array(ProtoCoreUtils.encode_varint(_timestamp))
		# Field map_name
		if _map_name != "":
			result.append_array(ProtoCoreUtils.encode_varint(26))
			var str_data: PackedByteArray = ProtoCoreUtils.encode_string(_map_name)
			result.append_array(ProtoCoreUtils.encode_varint(str_data.size()))
			result.append_array(str_data)
		return result



	func from_bytes(data: PackedByteArray) -> ProtoCoreUtils.ProtobufError:
		"""Deserialize message from bytes."""
		var offset: int = 0

		while offset < data.size():
			# Read field tag
			var tag_result := ProtoCoreUtils.decode_varint(data, offset)
			if tag_result.size == -1:
				return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
			var tag: int = tag_result.value
			offset += tag_result.size

			var field_number: int = ProtoCoreUtils.get_field_number(tag)
			var wire_type: int = ProtoCoreUtils.get_wire_type(tag)

			match field_number:
				1:
					# Field players
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					var msg_data: PackedByteArray = data.slice(offset, offset + length)
					var msg_item := Player.new()
					var msg_result := msg_item.from_bytes(msg_data)
					if msg_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
						return msg_result
					_players.append(msg_item)
					offset += length
				2:
					# Field timestamp
					var result := ProtoCoreUtils.decode_varint(data, offset)
					if result.size == -1:
						return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
					_timestamp = result.value
					offset += result.size
				3:
					# Field map_name
					var length_result := ProtoCoreUtils.decode_varint(data, offset)
					if length_result.size == -1:
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
					offset += length_result.size
					var length: int = length_result.value
					if offset + length > data.size():
						return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_MISMATCH
					_map_name = ProtoCoreUtils.decode_string(data, offset, length)
					offset += length
				_:
					# Skip unknown field
					match wire_type:
						0:  # Varint
							var skip_result := ProtoCoreUtils.decode_varint(data, offset)
							if skip_result.size == -1:
								return ProtoCoreUtils.ProtobufError.VARINT_NOT_FOUND
							offset += skip_result.size
						1:  # Fixed64
							offset += 8
						2:  # Length-delimited
							var skip_length_result := ProtoCoreUtils.decode_varint(data, offset)
							if skip_length_result.size == -1:
								return ProtoCoreUtils.ProtobufError.LENGTH_DELIMITED_SIZE_NOT_FOUND
							offset += skip_length_result.size + skip_length_result.value
						5:  # Fixed32
							offset += 4
						_:
							return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE

		return ProtoCoreUtils.ProtobufError.NO_ERRORS



	func to_text(indent_level: int = 0) -> String:
		"""Serialize message to protobuf text format."""
		var result: String = ""
		var indent: String = "\t".repeat(indent_level)

		# Repeated field players
		for item in _players:
			result += indent + "players {\n"
			result += item.to_text(indent_level + 1)
			result += indent + "}\n"

		# Field timestamp
		if _timestamp != 0:
			result += indent + "timestamp: " + str(_timestamp) + "\n"

		# Field map_name
		if _map_name != "":
			result += indent + "map_name: \"" + ProtoCoreUtils.escape_string_text_format(_map_name) + "\"\n"

		return result



	func from_text(text: String) -> ProtoCoreUtils.ProtobufError:
		"""Deserialize message from protobuf text format."""
		var pos: int = 0

		while pos < text.length():
			# Skip whitespace and comments
			pos = ProtoCoreUtils.skip_whitespace(text, pos)
			if pos >= text.length():
				break

			# Parse field name
			var name_result := ProtoCoreUtils.parse_identifier(text, pos)
			if "error" in name_result:
				push_error(name_result["error"])
				return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
			var field_name: String = name_result["value"]
			pos = name_result["pos"]

			# Skip whitespace before colon
			pos = ProtoCoreUtils.skip_whitespace(text, pos)

			# Match field name and parse value
			match field_name:
				"players":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					# Parse message
					if pos < text.length() and text[pos] == "{":
						pos = pos + 1  # Skip opening brace
						pos = ProtoCoreUtils.skip_whitespace(text, pos)

						# Extract message body
						var msg_start := pos
						var depth := 1
						while pos < text.length() and depth > 0:
							if text[pos] == "{":
								depth = depth + 1
							elif text[pos] == "}":
								depth = depth - 1
								if depth == 0:
									break
							pos = pos + 1

						var msg_text := text.substr(msg_start, pos - msg_start)
						pos = pos + 1  # Skip closing brace

						var msg_instance := Player.new()
						var parse_result := msg_instance.from_text(msg_text)
						if parse_result != ProtoCoreUtils.ProtobufError.NO_ERRORS:
							return parse_result
						_players.append(msg_instance)
				"timestamp":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var num_result := ProtoCoreUtils.parse_number(text, pos)
					if "error" in num_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_timestamp = int(num_result["value"])
					pos = num_result["pos"]
				"map_name":
					# Parse colon
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
					pos = ProtoCoreUtils.skip_whitespace(text, pos)

					var str_result := ProtoCoreUtils.parse_string_literal(text, pos)
					if "error" in str_result:
						return ProtoCoreUtils.ProtobufError.UNDEFINED_STATE
					_map_name = str_result["value"]
					pos = str_result["pos"]
				_:
					# Unknown field - skip it
					push_warning("Unknown field: " + field_name)
					# Try to skip the value
					pos = ProtoCoreUtils.skip_whitespace(text, pos)
					if pos < text.length() and text[pos] == ":":
						pos = pos + 1
						pos = ProtoCoreUtils.skip_whitespace(text, pos)
						if pos < text.length() and text[pos] == "{":
							# Skip message body
							var depth := 1
							pos = pos + 1
							while pos < text.length() and depth > 0:
								if text[pos] == "{":
									depth = depth + 1
								elif text[pos] == "}":
									depth = depth - 1
								pos = pos + 1
						else:
							# Skip to next field
							while pos < text.length() and text[pos] not in ["\n", "#"]:
								pos = pos + 1

		return ProtoCoreUtils.ProtobufError.NO_ERRORS



	func _to_string() -> String:
		"""Generate debug string representation."""
		var parts: Array[String] = []

		if _players.size() > 0:
			parts.append("players: " + str(_players))
		if _timestamp != 0:
			parts.append("timestamp: " + str(_timestamp))
		if _map_name != "":
			parts.append("map_name: " + str(_map_name))

		return "GameState { " + ", ".join(parts) + " }"

