class_name ProtoCoreUtils

extends RefCounted

# Generated by gogdproto
# Common Protocol Buffers utilities
# DO NOT EDIT



enum ProtobufError {
	NO_ERRORS = 0,
	VARINT_NOT_FOUND = -1,
	REPEATED_COUNT_NOT_FOUND = -2,
	REPEATED_COUNT_MISMATCH = -3,
	LENGTH_DELIMITED_SIZE_NOT_FOUND = -4,
	LENGTH_DELIMITED_SIZE_MISMATCH = -5,
	PACKAGE_SIZE_MISMATCH = -6,
	UNDEFINED_STATE = -7,
	PARSE_INCOMPLETE = -8,
	REQUIRED_FIELDS = -9,
}



const PROTO_VERSION: int = 3



# Encode/decode varint (variable-length integer)
static func encode_varint(value: int) -> PackedByteArray:
	"""Encode integer as varint."""
	var result: PackedByteArray = PackedByteArray()
	# Use unsigned right shift for proper varint encoding
	# Negative values will be encoded as large unsigned values (10 bytes)
	var unsigned_value: int = value
	while unsigned_value > 0x7F or unsigned_value < 0:
		result.append((unsigned_value & 0x7F) | 0x80)
		unsigned_value = (unsigned_value >> 7) & 0x01FFFFFFFFFFFFFF  # Unsigned right shift
	result.append(unsigned_value & 0x7F)
	return result

static func decode_varint(data: PackedByteArray, offset: int) -> Dictionary[String, int]:
	"""Decode varint from data.

	Returns:
	Dictionary with 'value' and 'size' keys
	"""
	var result: int = 0
	var shift: int = 0
	var size: int = 0

	while offset + size < data.size():
		var byte: int = data[offset + size]
		result |= (byte & 0x7F) << shift
		size += 1
		if (byte & 0x80) == 0:
			return {"value": result, "size": size}
		shift += 7
		if shift > 63:
			break

	return {"value": 0, "size": -1}

# Encode/decode zigzag (for sint32/sint64)
static func encode_zigzag32(value: int) -> int:
	"""Encode signed int32 using zigzag encoding."""
	# Mask final result to 32 bits to prevent 64-bit sign extension issues
	return (((value << 1) & 0xFFFFFFFF) ^ (value >> 31)) & 0xFFFFFFFF

static func encode_zigzag64(value: int) -> int:
	"""Encode signed int64 using zigzag encoding."""
	return (value << 1) ^ (value >> 63)

static func decode_zigzag32(value: int) -> int:
	"""Decode zigzag-encoded int32."""
	# Use conditional approach to avoid sign extension issues
	if value & 0x01:
		return ~(value >> 1)
	else:
		return value >> 1

static func decode_zigzag64(value: int) -> int:
	"""Decode zigzag-encoded int64."""
	# Need unsigned right shift for 64-bit values
	# Simulate unsigned right shift by masking after shift
	var shifted: int = (value >> 1) & 0x7FFFFFFFFFFFFFFF
	if value & 0x01:
		return ~shifted
	else:
		return shifted

# Encode/decode fixed-size integers
static func encode_fixed32(value: int) -> PackedByteArray:
	"""Encode 32-bit fixed integer."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(4)
	result.encode_u32(0, value)
	return result

static func encode_fixed64(value: int) -> PackedByteArray:
	"""Encode 64-bit fixed integer."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(8)
	result.encode_u64(0, value)
	return result

static func decode_fixed32(data: PackedByteArray, offset: int) -> int:
	"""Decode 32-bit unsigned fixed integer."""
	return data.decode_u32(offset)

static func decode_fixed64(data: PackedByteArray, offset: int) -> int:
	"""Decode 64-bit unsigned fixed integer."""
	return data.decode_u64(offset)

static func encode_sfixed32(value: int) -> PackedByteArray:
	"""Encode 32-bit signed fixed integer."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(4)
	result.encode_s32(0, value)
	return result

static func encode_sfixed64(value: int) -> PackedByteArray:
	"""Encode 64-bit signed fixed integer."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(8)
	result.encode_s64(0, value)
	return result

static func decode_sfixed32(data: PackedByteArray, offset: int) -> int:
	"""Decode 32-bit signed fixed integer."""
	return data.decode_s32(offset)

static func decode_sfixed64(data: PackedByteArray, offset: int) -> int:
	"""Decode 64-bit signed fixed integer."""
	return data.decode_s64(offset)

# Encode/decode float/double
static func encode_float(value: float) -> PackedByteArray:
	"""Encode 32-bit float."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(4)
	result.encode_float(0, value)
	return result

static func encode_double(value: float) -> PackedByteArray:
	"""Encode 64-bit double."""
	var result: PackedByteArray = PackedByteArray()
	result.resize(8)
	result.encode_double(0, value)
	return result

static func decode_float(data: PackedByteArray, offset: int) -> float:
	"""Decode 32-bit float."""
	return data.decode_float(offset)

static func decode_double(data: PackedByteArray, offset: int) -> float:
	"""Decode 64-bit double."""
	return data.decode_double(offset)

# Encode/decode string
static func encode_string(value: String) -> PackedByteArray:
	"""Encode string as UTF-8."""
	return value.to_utf8_buffer()

static func decode_string(data: PackedByteArray, offset: int, length: int) -> String:
	"""Decode UTF-8 string."""
	var slice: PackedByteArray = data.slice(offset, offset + length)
	return slice.get_string_from_utf8()

# Make field tag
static func make_tag(field_number: int, wire_type: int) -> int:
	"""Make protobuf field tag."""
	return (field_number << 3) | wire_type

# Get wire type from tag
static func get_wire_type(tag: int) -> int:
	"""Extract wire type from tag."""
	return tag & 0x7

# Get field number from tag
static func get_field_number(tag: int) -> int:
	"""Extract field number from tag."""
	return tag >> 3




# ============================================================================
# Text Format Utilities
# ============================================================================

# Text format escaping and unescaping
static func escape_string_text_format(value: String) -> String:
	"""Escape string for text format output."""
	var result: String = ""
	for i in range(value.length()):
		var ch = value[i]
		match ch:
			"\n": result += "\\n"
			"\r": result += "\\r"
			"\t": result += "\\t"
			"\"": result += "\\\""
			"\\": result += "\\\\"
			_:
				var code = ch.unicode_at(0)
				if code < 32:
					# Non-printable control characters: use \xHH escape
					result += "\\x%02x" % code
				else:
					# Preserve all other characters (including UTF-8)
					result += ch
	return result

static func escape_bytes_text_format(value: PackedByteArray) -> String:
	"""Escape bytes for text format output."""
	var result: String = ""
	for byte in value:
		if byte >= 32 and byte < 127 and byte != 92 and byte != 34:  # printable, not backslash or quote
			result += char(byte)
		else:
			result += "\\x%02x" % byte
	return result

static func unescape_string_text_format(value: String) -> String:
	"""Unescape text format string."""
	var result: String = ""
	var i: int = 0
	while i < value.length():
		var ch = value[i]
		if ch == "\\":
			i += 1
			if i >= value.length():
				break
			var next = value[i]
			match next:
				"n": result += "\n"
				"r": result += "\r"
				"t": result += "\t"
				"\\": result += "\\"
				"\"": result += "\""
				"x":
					# \xHH hex escape
					if i + 2 < value.length():
						var hex = value.substr(i + 1, 2)
						result += char(hex.hex_to_int())
						i += 2
				_:
					result += next
			i += 1
		else:
			result += ch
			i += 1
	return result

static func unescape_bytes_text_format(value: String) -> PackedByteArray:
	"""Unescape text format string directly to bytes."""
	var result := PackedByteArray()
	var i: int = 0
	while i < value.length():
		var ch = value[i]
		if ch == "\\":
			i += 1
			if i >= value.length():
				break
			var next = value[i]
			match next:
				"n": result.append(0x0A)  # \n
				"r": result.append(0x0D)  # \r
				"t": result.append(0x09)  # \t
				"\\": result.append(0x5C)  # \
				"\"": result.append(0x22)  # "
				"x":
					# \xHH hex escape - convert directly to byte
					if i + 2 < value.length():
						var hex = value.substr(i + 1, 2)
						result.append(hex.hex_to_int())
						i += 2
				_:
					# Unknown escape, just use the byte value of the character
					result.append(next.unicode_at(0))
			i += 1
		else:
			# Regular character - append its byte value
			result.append(ch.unicode_at(0))
			i += 1
	return result

# Text format parsing utilities
static func skip_whitespace(text: String, pos: int) -> int:
	"""Skip whitespace and comments."""
	while pos < text.length():
		var ch = text[pos]
		if ch in [" ", "\t", "\n", "\r"]:
			pos += 1
		elif ch == "#":
			# Skip comment until end of line
			while pos < text.length() and text[pos] != "\n":
				pos += 1
		else:
			break
	return pos

static func parse_identifier(text: String, pos: int) -> Dictionary:
	"""Parse identifier (field name or keyword)."""
	var start = pos
	while pos < text.length():
		var ch = text[pos]
		if ch.is_valid_identifier() or ch == "_" or (pos > start and ch.is_valid_int()):
			pos += 1
		else:
			break
	if pos == start:
		return {"error": "Expected identifier"}
	return {"value": text.substr(start, pos - start), "pos": pos}

static func parse_string_literal(text: String, pos: int) -> Dictionary:
	"""Parse quoted string literal."""
	if pos >= text.length() or text[pos] != "\"":
		return {"error": "Expected string literal"}
	pos += 1  # Skip opening quote
	var value: String = ""
	while pos < text.length():
		var ch = text[pos]
		if ch == "\"":
			pos += 1
			return {"value": value, "pos": pos}
		elif ch == "\\":
			pos += 1
			if pos >= text.length():
				return {"error": "Unterminated string"}
			var next = text[pos]
			match next:
				"n": value += "\n"
				"r": value += "\r"
				"t": value += "\t"
				"\\": value += "\\"
				"\"": value += "\""
				"x":
					if pos + 2 < text.length():
						var hex = text.substr(pos + 1, 2)
						value += char(hex.hex_to_int())
						pos += 2
				_:
					value += next
			pos += 1
		else:
			value += ch
			pos += 1
	return {"error": "Unterminated string"}

static func parse_number(text: String, pos: int) -> Dictionary:
	"""Parse number (int or float)."""
	var start = pos
	# Handle negative sign
	if pos < text.length() and text[pos] in ["-", "+"]:
		pos += 1
	# Check for special float values
	if pos + 2 < text.length():
		var substr = text.substr(pos, 3)
		if substr == "inf":
			return {"value": INF if text[start] != "-" else -INF, "pos": pos + 3, "is_float": true}
		if substr == "nan":
			return {"value": NAN, "pos": pos + 3, "is_float": true}
	# Parse digits
	var has_dot = false
	var has_exp = false
	while pos < text.length():
		var ch = text[pos]
		if ch.is_valid_int():
			pos += 1
		elif ch == "." and not has_dot and not has_exp:
			has_dot = true
			pos += 1
		elif ch in ["e", "E"] and not has_exp:
			has_exp = true
			pos += 1
			if pos < text.length() and text[pos] in ["+", "-"]:
				pos += 1
		else:
			break
	if pos == start or (pos == start + 1 and text[start] in ["-", "+"]):
		return {"error": "Expected number"}
	var num_str = text.substr(start, pos - start)
	if has_dot or has_exp:
		return {"value": float(num_str), "pos": pos, "is_float": true}
	else:
		return {"value": int(num_str), "pos": pos, "is_float": false}