package generator_test

import (
	"os"
	"strings"
	"testing"

	"github.com/cafecito-games/gogdproto/internal/ast"
	"github.com/cafecito-games/gogdproto/internal/generator"
	"github.com/cafecito-games/gogdproto/internal/lexer"
	"github.com/cafecito-games/gogdproto/internal/parser"
	"github.com/cafecito-games/gogdproto/internal/validator"
)

func TestGenerateEmptyProto(t *testing.T) {
	file := &ast.ProtoFile{Syntax: "proto3"}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if cls == nil {
		t.Fatal("Generate returned nil ClassDefinition")
	}
	if cls.ClassNameDirective != "ExampleProto" {
		t.Errorf("ClassNameDirective = %q, want %q", cls.ClassNameDirective, "ExampleProto")
	}
	if cls.Extends != "RefCounted" {
		t.Errorf("Extends = %q, want %q", cls.Extends, "RefCounted")
	}
	out := cls.ToGDScript(0)
	wantPrefix := "class_name ExampleProto\n\nextends RefCounted\n\n# Generated by gdproto\n# Source: example.proto\n# DO NOT EDIT\n"
	if !strings.HasPrefix(out, wantPrefix) {
		t.Errorf("output does not start with expected header; got first 200 chars:\n%q", out[:minInt(len(out), 200)])
	}
	if strings.Contains(out, "enum PB_ERR {") {
		t.Errorf("output should no longer contain PB_ERR enum")
	}
	if strings.Contains(out, "const PROTO_VERSION") {
		t.Errorf("output should no longer contain PROTO_VERSION constant")
	}
	if strings.Contains(out, "class PBCore") {
		t.Errorf("output should no longer contain class PBCore block")
	}
}

func TestGenerateHeaderUsesBasename(t *testing.T) {
	file := &ast.ProtoFile{Syntax: "proto3"}
	cls, err := generator.Generate(file, "/tmp/foo/bar_baz.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	if !strings.Contains(out, "# Source: bar_baz.proto") {
		t.Errorf("output should reference basename of input path; got first 200 chars:\n%q", out[:minInt(len(out), 200)])
	}
}

func TestGenerateTopLevelEnum(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Enums: []*ast.Enum{{
			Name: "PlayerStatus",
			Values: []*ast.EnumValue{
				{Name: "OFFLINE", Number: 0},
				{Name: "ONLINE", Number: 1},
				{Name: "AWAY", Number: 2},
				{Name: "IN_GAME", Number: 3},
			},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	if !strings.Contains(out, "enum PlayerStatus {") {
		t.Errorf("output missing PlayerStatus enum")
	}
	for _, want := range []string{"OFFLINE = 0", "ONLINE = 1", "AWAY = 2", "IN_GAME = 3"} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing enum entry %q", want)
		}
	}
}

func TestGenerateMessageClassShell(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Messages: []*ast.Message{{
			Name: "Player",
			Fields: []*ast.Field{
				{FieldType: "string", Name: "username", Number: 1},
				{FieldType: "int32", Name: "level", Number: 2},
				{FieldType: "string", Name: "inventory", Number: 5, Repeated: true},
			},
			NestedMessages: []*ast.Message{{
				Name: "Position",
				Fields: []*ast.Field{
					{FieldType: "float", Name: "x", Number: 1},
				},
			}},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		"class Player extends RefCounted:",
		"class Position extends RefCounted:",
		`var _username: String = ""`,
		"var _level: int = 0",
		"var _inventory: Array[String] = []",
		"var _x: float = 0.0",
		"func set_username(value: String) -> void:",
		"func get_username() -> String:",
		"func add_inventory(value: String) -> void:",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing fragment %q", want)
		}
	}
}

func TestGenerateAccessorBodies(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Enums: []*ast.Enum{{
			Name: "PlayerStatus",
			Values: []*ast.EnumValue{
				{Name: "OFFLINE", Number: 0},
				{Name: "ONLINE", Number: 1},
			},
		}},
		Messages: []*ast.Message{{
			Name: "Player",
			Fields: []*ast.Field{
				{FieldType: "string", Name: "username", Number: 1},
				{FieldType: "PlayerStatus", Name: "status", Number: 2},
				{FieldType: "Position", Name: "position", Number: 3},
				{FieldType: "string", Name: "inventory", Number: 4, Repeated: true},
			},
			Maps: []*ast.MapField{{
				Name:      "stats",
				KeyType:   "string",
				ValueType: "int32",
				Number:    5,
			}},
			Oneofs: []*ast.Oneof{{
				Name: "contact",
				Fields: []*ast.Field{
					{FieldType: "string", Name: "email", Number: 6},
				},
			}},
			NestedMessages: []*ast.Message{{
				Name: "Position",
				Fields: []*ast.Field{
					{FieldType: "float", Name: "x", Number: 1},
				},
			}},
		}, {
			Name: "GameState",
			Fields: []*ast.Field{
				{FieldType: "Player", Name: "players", Number: 1, Repeated: true},
			},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		// Scalar setter body
		"func set_username(value: String) -> void:\n\t\t_username = value",
		// Scalar getter body
		"func get_username() -> String:\n\t\treturn _username",
		// Enum-typed field uses message-like accessors and null default.
		"var _status: PlayerStatus = null",
		"func new_status() -> PlayerStatus:\n\t\t_status = PlayerStatus.new()\n\t\treturn _status",
		// Nested message field uses message-like accessor with new_.
		"func new_position() -> Position:\n\t\t_position = Position.new()\n\t\treturn _position",
		// Repeated scalar adds a value.
		"func add_inventory(value: String) -> void:\n\t\t_inventory.append(value)",
		// Repeated message adds, returns the new instance.
		"func add_players() -> Player:\n\t\tvar item: Player = Player.new()\n\t\t_players.append(item)\n\t\treturn item",
		// Map accessor inserts into dictionary.
		"func add_stats(key: String, value: int) -> void:\n\t\t_stats[key] = value",
		"func get_stats() -> Dictionary[String, int]:\n\t\treturn _stats",
		// Oneof setter updates the tracking variable and emits has_.
		"func set_email(value: String) -> void:\n\t\tif _oneof_contact != \"email\":\n\t\t\t_oneof_contact = \"email\"\n\t\t_email = value",
		"func has_email() -> bool:\n\t\treturn _oneof_contact == \"email\"",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing fragment:\n%s\n--- full output ---\n%s", want, out)
		}
	}
}

func TestGenerateToBytesScalar(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Messages: []*ast.Message{{
			Name: "Position",
			Fields: []*ast.Field{
				{FieldType: "float", Name: "x", Number: 1},
				{FieldType: "float", Name: "y", Number: 2},
				{FieldType: "float", Name: "z", Number: 3},
			},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		"func to_bytes() -> PackedByteArray:",
		`"""Serialize message to bytes."""`,
		"var result: PackedByteArray = PackedByteArray()",
		"# Field x",
		"if _x != 0.0:",
		"result.append_array(PBCore.encode_varint(13))",
		"result.append_array(PBCore.encode_float(_x))",
		"# Field z",
		"if _z != 0.0:",
		"result.append_array(PBCore.encode_varint(29))",
		"return result",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("to_bytes scalar output missing fragment %q\n--- full output ---\n%s", want, out)
		}
	}
}

func TestGenerateToBytesStringRepeatedMessageOneofMap(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Messages: []*ast.Message{{
			Name: "Player",
			Fields: []*ast.Field{
				{FieldType: "string", Name: "username", Number: 1},
				{FieldType: "Position", Name: "position", Number: 2},
				{FieldType: "string", Name: "inventory", Number: 3, Repeated: true},
			},
			Oneofs: []*ast.Oneof{{
				Name: "contact",
				Fields: []*ast.Field{
					{FieldType: "string", Name: "email", Number: 4},
				},
			}},
			Maps: []*ast.MapField{{
				Name:      "stats",
				KeyType:   "string",
				ValueType: "int32",
				Number:    5,
			}},
			NestedMessages: []*ast.Message{{
				Name: "Position",
				Fields: []*ast.Field{
					{FieldType: "float", Name: "x", Number: 1},
				},
			}},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		"# Field username",
		`if _username != "":`,
		"var str_data: PackedByteArray = PBCore.encode_string(_username)",
		"# Field position",
		"if _position != null:",
		"var msg_data: PackedByteArray = _position.to_bytes()",
		"# Field inventory (repeated)",
		"for item in _inventory:",
		"# Field email",
		`if _email != "":`,
		"# Map field stats",
		"for key in _stats:",
		"var value = _stats[key]",
		"# Build map entry",
		"var entry: PackedByteArray = PackedByteArray()",
		"# Entry field 1: key",
		"var key_data: PackedByteArray = PBCore.encode_string(key)",
		"# Entry field 2: value",
		"entry.append_array(PBCore.encode_varint(value))",
		"# Append entry to result",
		"result.append_array(PBCore.encode_varint(42))",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("to_bytes complex output missing fragment %q\n--- full output ---\n%s", want, out)
		}
	}
}

func TestGenerateFromBytesScalar(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Messages: []*ast.Message{{
			Name: "Position",
			Fields: []*ast.Field{
				{FieldType: "float", Name: "x", Number: 1},
				{FieldType: "float", Name: "y", Number: 2},
				{FieldType: "float", Name: "z", Number: 3},
			},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		"func from_bytes(data: PackedByteArray) -> int:",
		`"""Deserialize message from bytes."""`,
		"var offset: int = 0",
		"while offset < data.size():",
		"# Read field tag",
		"var tag_result: Dictionary = PBCore.decode_varint(data, offset)",
		"if tag_result.size == -1:",
		"return PB_ERR.VARINT_NOT_FOUND",
		"var field_number: int = PBCore.get_field_number(tag)",
		"var wire_type: int = PBCore.get_wire_type(tag)",
		"match field_number:",
		"# Field x",
		"if offset + 4 > data.size():",
		"return PB_ERR.PARSE_INCOMPLETE",
		"_x = PBCore.decode_float(data, offset)",
		"offset += 4",
		"# Skip unknown field",
		"match wire_type:",
		"return PB_ERR.UNDEFINED_STATE",
		"return PB_ERR.NO_ERRORS",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("from_bytes scalar output missing fragment %q\n--- full output ---\n%s", want, out)
		}
	}
}

func TestGenerateFromBytesComplex(t *testing.T) {
	file := &ast.ProtoFile{
		Syntax: "proto3",
		Messages: []*ast.Message{{
			Name: "Player",
			Fields: []*ast.Field{
				{FieldType: "string", Name: "username", Number: 1},
				{FieldType: "int32", Name: "level", Number: 2},
				{FieldType: "Position", Name: "position", Number: 3},
				{FieldType: "string", Name: "inventory", Number: 4, Repeated: true},
				{FieldType: "Player", Name: "friends", Number: 5, Repeated: true},
			},
			Maps: []*ast.MapField{{
				Name:      "stats",
				KeyType:   "string",
				ValueType: "int32",
				Number:    6,
			}},
		}},
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := cls.ToGDScript(0)
	for _, want := range []string{
		"# Field username",
		"_username = PBCore.decode_string(data, offset, length)",
		"# Field level",
		"var result = PBCore.decode_varint(data, offset)",
		"_level = result.value",
		"# Field position",
		"_position = Position.new()",
		"var msg_result = _position.from_bytes(msg_data)",
		"if msg_result != PB_ERR.NO_ERRORS:",
		"# Field inventory",
		"_inventory.append(PBCore.decode_string(data, offset, length))",
		"# Field friends",
		"var msg_item = Player.new()",
		"_friends.append(msg_item)",
		"# Map field stats",
		"var entry_data: PackedByteArray = data.slice(offset, offset + length)",
		"var entry_offset: int = 0",
		`var map_key = ""`,
		"var map_value = 0",
		"match entry_field_number:",
		"# Entry key",
		"map_key = PBCore.decode_string(entry_data, entry_offset, str_len)",
		"# Entry value",
		"map_value = result.value",
		"_stats[map_key] = map_value",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("from_bytes complex output missing fragment %q\n--- full output ---\n%s", want, out)
		}
	}
}

func TestGoldenExample(t *testing.T) {
	// TODO(M7-T6): remove this skip once the generator output matches the
	// updated 1300-line golden byte-for-byte. T0 only fixes the wrapper
	// prefix; the body still diverges (PBCore -> ProtoCoreUtils, oneof
	// enums, text-format to_string, from_text_format).
	t.Skip("M7 in progress; will pass at T6")
	src, err := os.ReadFile("../../examples/example.proto")
	if err != nil {
		t.Fatalf("read example.proto: %v", err)
	}
	tokens, err := lexer.Tokenize(string(src), "example.proto")
	if err != nil {
		t.Fatalf("tokenize: %v", err)
	}
	file, err := parser.Parse(tokens, "example.proto")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if errs := validator.Validate(file, "example.proto"); len(errs) != 0 {
		t.Fatalf("validation errors: %+v", errs)
	}
	cls, err := generator.Generate(file, "example.proto")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	got := cls.ToGDScript(0)
	if !strings.HasSuffix(got, "\n") {
		got += "\n"
	}
	wantBytes, err := os.ReadFile("../../examples/golden.gd")
	if err != nil {
		t.Fatalf("read golden.gd: %v", err)
	}
	want := string(wantBytes)
	if got == want {
		return
	}
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			t.Fatalf("first diff at line %d:\n  got:  %q\n  want: %q", i+1, gotLines[i], wantLines[i])
		}
	}
	if len(gotLines) != len(wantLines) {
		t.Fatalf("line count mismatch: got %d, want %d", len(gotLines), len(wantLines))
	}
}

func TestProtoCoreUtilsGolden(t *testing.T) {
	got := generator.GenerateProtoCoreUtilsRaw()
	wantBytes, err := os.ReadFile("../../examples/proto_core_utils_golden.gd")
	if err != nil {
		t.Fatalf("read proto_core_utils_golden.gd: %v", err)
	}
	want := string(wantBytes)
	if got == want {
		return
	}
	gotLines := strings.Split(got, "\n")
	wantLines := strings.Split(want, "\n")
	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			t.Errorf("first diff at line %d:\n  got:  %q\n  want: %q", i+1, gotLines[i], wantLines[i])
			break
		}
	}
	if len(gotLines) != len(wantLines) {
		t.Errorf("line counts: got %d, want %d", len(gotLines), len(wantLines))
	}
}

func TestWrapperClassName(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"example.proto", "ExampleProto"},
		{"foo/bar.proto", "FooBarProto"},
		{"PlayerStats.proto", "PlayerStatsProto"},
		{"google/protobuf/timestamp.proto", "GoogleProtobufTimestampProto"},
		{"player_stats.proto", "PlayerStatsProto"},
		{"123bad.proto", "Proto123badProto"},
	}
	for _, tc := range cases {
		got := generator.WrapperClassNameForTest(tc.in)
		if got != tc.want {
			t.Errorf("wrapperClassName(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}
